Repository defold/defold, pull requests merged in 2022-11, with the labels that each got.

#7156 Fix issue with long bytecode delta calculation
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/LuaBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/LuaBuilder.java
Labels: skip release notes

#7171 Fix crash when max sound instances is 0
  engine/gamesys/src/gamesys/components/comp_sound.cpp
Labels: bug, engine

#7154 Create texture resource in runtime
  engine/gameobject/src/gameobject/gameobject.cpp
  engine/gameobject/src/gameobject/gameobject.h
  engine/gameobject/src/gameobject/gameobject_private.h
  engine/gameobject/src/gameobject/gameobject_profile.cpp
  engine/gamesys/src/gamesys/resources/res_texture.cpp
  engine/gamesys/src/gamesys/scripts/script_resource.cpp
  engine/gamesys/src/gamesys/test/resource/create_texture.go
  engine/gamesys/src/gamesys/test/resource/create_texture.script
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/graphics/src/graphics.h
  engine/graphics/src/graphics_private.h
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/resource/src/resource.cpp
  engine/resource/src/resource.h
  engine/resource/src/resource_private.h
Labels: feature request
