Repository defold/defold, pull requests merged in 2023-07, with the labels that each got.

#7792 Fix issue when `arm64-macos` can't be bundle without bundling `x86_64-macos`
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/MacOSBundler.java
Labels: skip release notes

#7772 Update all cameras in the focus stack
  engine/engine/src/test/camera/camera_acquire_input_focus.collection
  engine/engine/src/test/camera/camera_acquire_input_focus.go
  engine/engine/src/test/camera/camera_acquire_input_focus.render
  engine/engine/src/test/camera/camera_acquire_input_focus.render_script
  engine/engine/src/test/camera/camera_acquire_input_focus.script
  engine/engine/src/test/test_engine.cpp
  engine/gamesys/src/gamesys/components/comp_camera.cpp
Labels: feature request, engine

#7803 Material constant array support for go.get/go.set
  engine/engine/src/test/script_props/uniform_property.script
  engine/gameobject/src/dmsdk/gameobject/gameobject.h
  engine/gameobject/src/gameobject/gameobject.cpp
  engine/gameobject/src/gameobject/gameobject.h
  engine/gameobject/src/gameobject/gameobject_script.cpp
  engine/gamesys/src/gamesys/gamesys_private.cpp
Labels: feature request

#7815 Better error message for mustache templater
  com.dynamo.cr/com.dynamo.cr.bob/build.xml
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/BundleHelper.java
Labels: skip release notes

#7824 Fix Bob tests for arm64-osx
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/bundle/test/BundlerTest.java
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/BundleResourcesTest.java
  com.dynamo.cr/com.dynamo.cr.bob.test/testextension/restest2/arm64-osx/arm64-osx.txt
Labels: skip release notes

#7830 Make sure editor starts on windows
  editor/src/java/com/defold/editor/Start.java
Labels: skip release notes

#7834 fix profiler types
  engine/gui/src/gui.cpp
Labels: skip release notes

#7813 Sound stopped event
  engine/gamesys/proto/gamesys/gamesys_ddf.proto
  engine/gamesys/src/gamesys/components/comp_sound.cpp
  engine/gamesys/src/gamesys/scripts/script_sound.cpp
  engine/gamesys/src/gamesys/test/sound/luacallback.script
Labels: feature request, engine
