Repository defold/defold, pull requests merged in 2023-01, with the labels that each got.

#7244 Conform 'buffer is full' error messages
  engine/gamesys/src/gamesys/components/comp_camera.cpp
  engine/gamesys/src/gamesys/components/comp_collection_factory.cpp
  engine/gamesys/src/gamesys/components/comp_collection_proxy.cpp
  engine/gamesys/src/gamesys/components/comp_collision_object.cpp
  engine/gamesys/src/gamesys/components/comp_factory.cpp
  engine/gamesys/src/gamesys/components/comp_gui.cpp
  engine/gamesys/src/gamesys/components/comp_label.cpp
  engine/gamesys/src/gamesys/components/comp_mesh.cpp
  engine/gamesys/src/gamesys/components/comp_model.cpp
  engine/gamesys/src/gamesys/components/comp_particlefx.cpp
  engine/gamesys/src/gamesys/components/comp_sound.cpp
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/gamesys/src/gamesys/components/comp_tilegrid.cpp
  engine/gamesys/src/gamesys/gamesys_private.cpp
  engine/gamesys/src/gamesys/gamesys_private.h
Labels: bug, engine

#7259 Vulkan bugfixes
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilder.java
  engine/graphics/src/vulkan/graphics_vulkan.cpp
Labels: bug, render, vulkan

#7267 Support bin zip files in addition to plugin bin dir
  editor/src/clj/editor/fs.clj
  editor/src/clj/editor/workspace.clj
  editor/test/integration/engine/native_extensions_test.clj
  editor/test/integration/spine_extension_test.clj
  editor/test/resources/extension_project/.gitignore
  editor/test/resources/extension_project/ext_with_bin_zip/ext.manifest
  editor/test/resources/extension_project/ext_with_bin_zip/plugins/bin/x86_64-macos.zip
Labels: skip release notes

#7272 Issue 6654 - fixes broken tests on build-size report
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/archive/ArchiveReader.java
Labels: skip release notes

#6902 Issue 6892: Shader include support
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderProgramBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob.test/test/glsl_same_folder.glsl
  com.dynamo.cr/com.dynamo.cr.bob.test/test/glsl_sub_include_from_multi.glsl
  com.dynamo.cr/com.dynamo.cr.bob.test/test/shader_includes/glsl_cyclic_include.glsl
  com.dynamo.cr/com.dynamo.cr.bob.test/test/shader_includes/glsl_cyclic_include_other.glsl
  com.dynamo.cr/com.dynamo.cr.bob.test/test/shader_includes/glsl_self_include.glsl
  com.dynamo.cr/com.dynamo.cr.bob.test/test/shader_includes/glsl_sub_include.glsl
  com.dynamo.cr/com.dynamo.cr.bob.test/test/shader_includes/glsl_sub_include_multi.glsl
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/CopyBuilders.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/FragmentProgramBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderPreprocessor.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderUtil.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/VertexProgramBuilder.java
  editor/resources/templates/template.glsl
  editor/src/clj/editor/code/shader.clj
  editor/src/clj/editor/workspace.clj
  editor/styling/stylesheets/mixins/_file-extensions.scss
Labels: feature request, engine, render

#7279 Use plugins zips instead of bin zips
  editor/src/clj/editor/workspace.clj
  editor/test/integration/engine/native_extensions_test.clj
  editor/test/resources/extension_project/ext_with_bin_zip/plugins/bin/x86_64-macos.zip
  editor/test/resources/extension_project/ext_with_bin_zip/plugins/x86_64-linux.zip
  editor/test/resources/extension_project/ext_with_bin_zip/plugins/x86_64-macos.zip
  editor/test/resources/extension_project/ext_with_bin_zip/plugins/x86_64-win32.zip
Labels: skip release notes

#7268 Make bob extract plugin bin zips
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ExtenderUtil.java
Labels: skip release notes

#7285 Support creating texture with buffer directly in resource.create
  engine/gamesys/src/gamesys/scripts/script_resource.cpp
  engine/gamesys/src/gamesys/scripts/script_window.cpp
  engine/gamesys/src/gamesys/test/resource/create_texture.script
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/tools/src/texconvert/main.cpp
Labels: feature request

#7308 fixes mesh culling algorithm
  engine/dlib/src/dlib/intersection.cpp
  engine/dlib/src/test/test_intersection.cpp
Labels: skip release notes

#7289 Bob debugging doc
  com.dynamo.cr/com.dynamo.cr.bob/README.md
Labels: skip release notes

#7318 Add a visualizer for internal node dependencies
  editor/project.clj
  editor/src/clj/editor/gviz.clj
Labels: skip release notes

#7319 Make bob skip the build dir
  editor/src/clj/editor/pipeline/bob.clj
Labels: skip release notes

#7325 Fix Dependencies and Referencing Files popup showing blank entries for some resource types
  editor/src/clj/dynamo/graph.clj
  editor/src/clj/editor/core.clj
  editor/src/clj/editor/resource_dialog.clj
  editor/src/clj/editor/resource_node.clj
  editor/src/clj/editor/workspace.clj
  editor/test/integration/test_util.clj
Labels: bug, editor

#7340 Fix NullPointerException when building or opening certain gui scenes from the editor
  editor/src/clj/editor/core.clj
  editor/src/clj/editor/gviz.clj
  editor/src/clj/editor/resource_dialog.clj
  editor/src/clj/editor/resource_node.clj
Labels: bug, editor, gui

#7343 Show error in bob when referencing missing script resource properties
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/LuaBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/CollectionBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/LuaBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/LuaScanner.java
Labels: bug
