Repository defold/defold, pull requests merged in 2023-12, with the labels that each got.

#8247 Wrap glfw calls in dmPlatform library
  build_tools/waf_dynamo.py
  engine/engine/src/engine.cpp
  engine/engine/src/engine_private.h
  engine/engine/src/test/test_engine.cpp
  engine/engine/src/test/wscript
  engine/engine/src/wscript
  engine/engine/wscript
  engine/gamesys/src/gamesys/test/fontview/fontview.cpp
  engine/gamesys/src/gamesys/test/fontview/fontview.h
  engine/gamesys/src/gamesys/test/fontview/wscript
  engine/gamesys/src/gamesys/test/test_gamesys.h
  engine/gamesys/src/gamesys/test/wscript
  engine/gamesys/wscript
  engine/graphics/src/graphics.cpp
  engine/graphics/src/graphics.h
  engine/graphics/src/graphics_adapter.h
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/null/graphics_null_private.h
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/opengl/graphics_opengl_private.h
  engine/graphics/src/test/test_app_vulkan.cpp
  engine/graphics/src/test/test_graphics.cpp
  engine/graphics/src/test/wscript
  engine/graphics/src/vulkan/graphics_native.cpp
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan_private.h
  engine/hid/src/hid.cpp
  engine/hid/src/hid.h
  engine/hid/src/hid_null.cpp
  engine/hid/src/hid_private.h
  engine/hid/src/native/hid_gamepad_driver_glfw.cpp
  engine/hid/src/native/hid_native.cpp
  engine/hid/src/test/test_app_hid.cpp
  engine/hid/src/test/test_hid.cpp
  engine/input/src/input.cpp
  engine/platform/src/platform_window.h
  engine/platform/src/platform_window_glfw.cpp
  engine/platform/src/platform_window_null.cpp
  engine/platform/src/test/test_platform.cpp
  engine/platform/src/test/test_platform_app.cpp
  engine/platform/src/test/wscript
  engine/platform/src/wscript
  engine/platform/wscript
  engine/render/src/test/test_material.cpp
  engine/render/src/test/test_render.cpp
  engine/render/src/test/test_render_script.cpp
  engine/render/src/test/wscript
  engine/render/wscript
  engine/tools/src/gdc/main.cpp
  engine/tools/src/gdc/wscript
  engine/tools/src/launcher/test/wscript
  engine/tools/src/texconvert/wscript
  engine/tools/wscript
  scripts/build.py
  share/extender/build_input.yml
Labels: engine

#8290 Bugfix for sprite page indices
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
Labels: skip release notes

#8279 Update glslc to support macos 11 for arm64 and remove old glslc archives (duplicates we don't use anymore)
  packages/glslc-31bddbb-arm64-macos.tar.gz
  packages/glslc-31bddbb-x86_64-macos.tar.gz
  packages/glslc-40bced4-arm64-macos.tar.gz
  packages/glslc-40bced4-x86_64-macos.tar.gz
  packages/glslc-96b1dd7-arm64-macos.tar.gz
  packages/glslc-96b1dd7-x86_64-linux.tar.gz
  packages/glslc-96b1dd7-x86_64-macos.tar.gz
  scripts/build.py
  share/ext/glslc/build_glslc.sh
Labels: skip release notes

#8301 Add save data tests for multiple materials in models
  editor/test/integration/save_data_test.clj
  editor/test/resources/save_data_project/checked.material
  editor/test/resources/save_data_project/checked.model
  editor/test/resources/save_data_project/referenced/mesh.glb
  editor/test/resources/save_data_project/referenced/model.material
  editor/test/resources/save_data_project/silently_migrated/legacy_material_and_textures.model
Labels: skip release notes

#8302 Annotate protobuf fields as runtime-only to ignore in save data tests
  editor/src/clj/editor/code/util.clj
  editor/test/integration/save_data_test.clj
  engine/ddf/src/ddf/ddf_extensions.proto
  engine/gameobject/proto/gameobject/gameobject_ddf.proto
  engine/gamesys/proto/gamesys/tile_ddf.proto
  engine/graphics/proto/graphics/graphics_ddf.proto
  engine/render/proto/render/material_ddf.proto
Labels: skip release notes

#8314 Remove GD template
  editor/resources/welcome/images/gamedistribution.svg
  editor/resources/welcome/welcome.edn
Labels: skip release notes

#8328 Fixed support for generating macOS symbols on the extender.
  share/extender/build_input.yml
Labels: extender

#8331 Delay creation of the platform bundler until it's needed
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/BundleHelper.java
Labels: skip release notes

#8340 Fix 'could not find render socket' error
  engine/platform/src/platform_window_glfw.cpp
Labels: skip release notes

#8300 Dynamic resizing of collision shapes
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ProtoBuilders.java
  editor/src/clj/editor/collision_object.clj
  editor/test/resources/save_data_project/checked01.collisionobject
  engine/gamesys/proto/gamesys/physics_ddf.proto
  engine/gamesys/src/dmsdk/gamesys/resources/res_collision_object.h
  engine/gamesys/src/gamesys/components/comp_collision_object.cpp
  engine/gamesys/src/gamesys/components/comp_collision_object.h
  engine/gamesys/src/gamesys/resources/res_collision_object.cpp
  engine/gamesys/src/gamesys/scripts/script_physics.cpp
  engine/gamesys/src/gamesys/test/collision_object/get_set_shape.collisionobject
  engine/gamesys/src/gamesys/test/collision_object/get_set_shape.go
  engine/gamesys/src/gamesys/test/collision_object/get_set_shape.script
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/gamesys/src/waf_gamesys.py
  engine/physics/src/box2d/Box2D/Dynamics/b2Body.h
  engine/physics/src/physics/physics.h
  engine/physics/src/physics/physics_2d.cpp
  engine/physics/src/physics/physics_3d.cpp
Labels: feature request, engine, physics

#8344 Buffered render buffers support
  engine/gamesys/src/gamesys/components/comp_model.cpp
  engine/gamesys/src/gamesys/components/comp_particlefx.cpp
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/gamesys/src/gamesys/components/comp_tilegrid.cpp
  engine/graphics/src/graphics.h
  engine/graphics/src/graphics_private.h
  engine/render/src/render/buffer.cpp
  engine/render/src/render/render.cpp
  engine/render/src/render/render.h
  engine/render/src/render/render_private.h
  engine/render/src/test/test_render.cpp
  engine/render/src/test/test_render_buffer.cpp
  engine/render/src/test/wscript
Labels: engine, vulkan
