Repository defold/defold, pull requests merged in 2023-11, with the labels that each got.

#8202 Reorder shader languages to avoid major version bump
  engine/graphics/proto/graphics/graphics_ddf.proto
Labels: skip release notes

#8211 Disable Show/Hide Selected Objects command when nothing is selected
  editor/src/clj/editor/debug_view.clj
  editor/src/clj/editor/scene_visibility.clj
Labels: bug, editor

#8216 Bugfix for vulkan fullscreen support on OSX
  engine/glfw/lib/cocoa/cocoa_window.m
Labels: bug, engine, vulkan

#8215 Use 'am' instead of 'monkey' to perform an Android app launch
  editor/src/clj/editor/adb.clj
Labels: more info, editor

#8230 Vulkan experimental api additions
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderCompilerHelpers.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderUtil.java
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/graphics/proto/graphics/graphics_ddf.proto
  engine/graphics/src/dmsdk/graphics/graphics.h
  engine/graphics/src/graphics.cpp
  engine/graphics/src/graphics.h
  engine/graphics/src/graphics_adapter.h
  engine/graphics/src/graphics_private.h
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/test/test_app_vulkan.cpp
  engine/graphics/src/test/test_app_vulkan.fs
  engine/graphics/src/test/test_app_vulkan.fs.spv
  engine/graphics/src/test/test_app_vulkan.vs
  engine/graphics/src/test/test_app_vulkan.vs.spv
  engine/graphics/src/test/test_app_vulkan_assets.h
  engine/graphics/src/test/test_app_vulkan_package_assets.py
  engine/graphics/src/test/test_graphics.cpp
  engine/graphics/src/test/wscript
  engine/graphics/src/vulkan/android/graphics_vulkan_android.cpp
  engine/graphics/src/vulkan/graphics_native.cpp
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan.h
  engine/graphics/src/vulkan/graphics_vulkan_context.cpp
  engine/graphics/src/vulkan/graphics_vulkan_device.cpp
  engine/graphics/src/vulkan/graphics_vulkan_dynamic.h
  engine/graphics/src/vulkan/graphics_vulkan_private.h
  engine/graphics/src/vulkan/graphics_vulkan_swap_chain.cpp
  engine/render/src/render/render.cpp
  engine/render/src/render/render.h
Labels: skip release notes

#8236 Make sure that symbols for default `dmengine` copied right
  build_tools/waf_dynamo.py
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Bob.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/IOSBundler.java
Labels: skip release notes

#8239 Update MVK packages
  engine/graphics/src/vulkan/README.md
  packages/moltenvk-1.3.261.1-arm64-macos.tar.gz
  packages/moltenvk-1.3.261.1-x86_64-macos.tar.gz
Labels: skip release notes

#8229 Remove unneeded files from `_unpack` folder
  editor/scripts/bundle.py
  editor/tasks/leiningen/pack.clj
Labels: skip release notes

#8246 LU should be enabled if it's not disabled by `game.project` setting
  engine/liveupdate/src/liveupdate.cpp
Labels: skip release notes

#8244 Add support for luminance_alpha in image.load
  engine/dlib/src/dlib/image.cpp
  engine/dlib/src/dlib/image.h
  engine/dlib/src/dmsdk/dlib/image.h
  engine/dlib/src/test/test_image.cpp
  engine/script/src/script_image.cpp
Labels: task, dmsdk

#8249 Refactor resource bindings creations for Vulkan programs
  engine/graphics/src/graphics.cpp
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan_private.h
Labels: skip release notes

#8242 Use the WebGL 1.0 specific constant for the half float format.
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/opengl/graphics_opengl_defines.h
Labels: bug, engine

#8271 Use `sys.get_config_number()` instead of `sys.get_config_int()` in `default.render_script`
  engine/engine/content/builtins/render/default.render_script
Labels: skip release notes

#8270 Improve memory usage in large projects
  editor/src/clj/dynamo/graph.clj
  editor/src/clj/editor/pipeline.clj
  editor/src/clj/editor/protobuf.clj
  editor/src/clj/internal/graph/types.clj
  editor/src/java/com/defold/util/WeakInterner.java
  editor/test/editor/protobuf_test.clj
  editor/test/util/weak_interner_test.clj
Labels: editor

#8276 Fix asan nightly test
  engine/graphics/src/null/glsl_uniform_parser.cpp
Labels: skip release notes

#8278 Fix for compiling sprites using the old tile_set variable
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/CollectionBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ProtoBuilders.java
Labels: bob, sprite, skip release notes
