Repository defold/defold, pull requests merged in 2023-10, with the labels that each got.

#8051 Add ext build script for glfw3
  share/ext/glfw/build_glfw.sh
Labels: skip release notes

#8094 Added Warnament and Craftomation 101 to editor splash screen
  editor/resources/games/craftomation101.jpg
  editor/resources/games/warnament.jpg
  editor/src/java/com/defold/editor/Splash.java
Labels: skip release notes

#8096 Make sure we take into splash rotation the last image in the list
  editor/src/java/com/defold/editor/Splash.java
Labels: skip release notes

#8083 Support uniform buffers for Vulkan
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderProgramBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderCompilerHelpers.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderUtil.java
  engine/gamesys/src/gamesys/gamesys_private.cpp
  engine/graphics/proto/graphics/graphics_ddf.proto
  engine/graphics/src/dmsdk/graphics/graphics.h
  engine/graphics/src/graphics.cpp
  engine/graphics/src/graphics.h
  engine/graphics/src/graphics_adapter.h
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan_private.h
  engine/render/src/dmsdk/render/render.h
  engine/render/src/render/constant.cpp
  engine/render/src/render/material.cpp
  engine/render/src/render/render.h
  engine/render/src/render/render_private.h
  engine/render/src/test/test_material.cpp
Labels: engine, bob, graphics, skip release notes

#8093 Add TEXTURE_FORMAT_RGBA32UI support for vulkan
  engine/graphics/src/dmsdk/graphics/graphics.h
  engine/graphics/src/graphics.cpp
  engine/graphics/src/vulkan/graphics_vulkan.cpp
Labels: engine, dmsdk, skip release notes

#8122 Fix non-working Z handles on the Scale Manipulator
  editor/src/clj/editor/scene_tools.clj
Labels: bug, editor

#8069 Generate engine protobuf files for .compute shaders in Bob
  build_tools/waf_dynamo.py
  com.dynamo.cr/com.dynamo.cr.bob.test/build.xml
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ParseUtil.java
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderProgramBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ComputeProgramBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderCompilerHelpers.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderCompilers.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderUtil.java
  engine/gamesys/src/gamesys/test/shader/valid.compute
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/gamesys/src/gamesys/test/test_gamesys.h
  engine/gamesys/src/gamesys/test/wscript
  engine/gamesys/src/waf_gamesys.py
  engine/graphics/proto/graphics/graphics_ddf.proto
  scripts/unpack_ddf.py
Labels: engine, skip release notes

#8152 OpenGL renderer disables only enabled vertex attribute arrays
  engine/graphics/src/opengl/graphics_opengl.cpp
Labels: bug, engine

#8162 Detect comments in compiler derectives in GLSL Lexer
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderProgramBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/antlr/glsl/GLSLLexer.g4
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/antlr/glsl/GLSLLexer.java
Labels: skip release notes

#8177 Merge from internal repositories
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderCompilerHelpers.java
  engine/dlib/src/dlib/dalloca.h
  engine/dlib/src/dlib/memory.cpp
  engine/dlib/src/dmsdk/dlib/hash.h
  engine/dlib/src/dmsdk/dlib/memory.h
  engine/dlib/src/wscript
  engine/engine/content/builtins/assets/images/logo/logo_blue_1024.png
  engine/engine/content/builtins/assets/images/logo/logo_blue_512.png
  engine/engine/content/builtins/input/default.gamepads
  engine/gamesys/src/gamesys/test/fragment_program/valid.fp
  engine/gamesys/src/gamesys/test/material/attributes.vp
  engine/gamesys/src/gamesys/test/material/material_constant_array.fp
  engine/gamesys/src/gamesys/test/vertex_program/valid.vp
  engine/gamesys/src/gamesys/test/wscript
  engine/graphics/src/graphics.cpp
  engine/graphics/src/graphics_private.h
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan_device.cpp
  engine/graphics/src/vulkan/graphics_vulkan_private.h
  engine/hid/src/test/wscript
  engine/resource/src/providers/provider_archive_mutable.cpp
  engine/resource/src/providers/provider_archive_private.cpp
  engine/resource/src/resource.cpp
  engine/resource/src/resource_manifest.cpp
  engine/resource/src/resource_mounts.cpp
  engine/resource/src/resource_util.cpp
  engine/resource/src/resource_verify.cpp
  engine/resource/src/test/wscript
  engine/sdk/src/test/wscript
  engine/texc/src/texc_enc_basis.cpp
Labels: skip release notes

#8181 Compute shader creation in render and graphics libraries
  engine/graphics/src/graphics.cpp
  engine/graphics/src/graphics.h
  engine/graphics/src/graphics_adapter.h
  engine/graphics/src/null/glsl_uniform_parser.cpp
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/test/test_graphics.cpp
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan_private.h
  engine/render/src/render/compute.cpp
  engine/render/src/render/material.cpp
  engine/render/src/render/program_utils.cpp
  engine/render/src/render/render.h
  engine/render/src/render/render_private.h
Labels: skip release notes

#8191 Create constants with same name once for vulkan
  engine/graphics/src/graphics.cpp
  engine/graphics/src/graphics.h
  engine/graphics/src/graphics_adapter.h
  engine/graphics/src/graphics_private.h
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/opengl/graphics_opengl_private.h
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan_private.h
  engine/render/src/render/compute.cpp
  engine/render/src/render/material.cpp
  engine/render/src/render/program_utils.cpp
  engine/render/src/render/render_private.h
Labels: skip release notes

#8178 Added swift compilation commands to build.yml
  share/extender/build_input.yml
Labels: skip release notes
