Repository defold/defold, pull requests merged in 2023-08, with the labels that each got.

#7800 Add option to avoid copying or cloning buffer in resource.set_buffer
  engine/gamesys/src/gamesys/scripts/script_buffer.cpp
  engine/gamesys/src/gamesys/scripts/script_resource.cpp
  engine/gamesys/src/gamesys/test/resource/script_buffer.script
Labels: feature request, engine, buffer

#7849 Get and set node materials from gui scripts
  engine/engine/src/test/gui/material_script_functions.collection
  engine/engine/src/test/gui/material_script_functions.go
  engine/engine/src/test/gui/material_script_functions.gui
  engine/engine/src/test/gui/material_script_functions.gui_script
  engine/engine/src/test/gui/material_script_functions.script
  engine/engine/src/test/gui/material_script_functions_a.material
  engine/engine/src/test/gui/material_script_functions_b.material
  engine/engine/src/test/gui/material_script_functions_c.material
  engine/engine/src/test/test_engine.cpp
  engine/gamesys/src/gamesys/components/comp_gui.cpp
  engine/gamesys/src/gamesys/components/comp_label.cpp
  engine/gamesys/src/gamesys/gamesys_private.h
  engine/gamesys/src/gamesys/scripts/script_resource.cpp
  engine/gui/src/gui.cpp
  engine/gui/src/gui.h
  engine/gui/src/gui_private.h
  engine/gui/src/gui_script.cpp
Labels: feature request, engine, gui

#7858 Revert "Replaced deprecated spinlock implementation for Darwin (#7776)"
  engine/dlib/src/dmsdk/dlib/spinlocktypes_mach.h
Labels: skip release notes

#7859 Public key is a resource in archive and should use `ResourceExist()` function
  engine/resource/src/resource.cpp
Labels: skip release notes

#7871 fix typo in AndroidBundler
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/AndroidBundler.java
Labels: skip release notes

#7872 Fix crash in `store_manifest` when try to do so from the editor
  engine/liveupdate/src/liveupdate.cpp
Labels: skip release notes

#7873 A couple of extra logs which may help with HTTP-server test fail on Windows
  engine/dlib/src/test/http_server/TestHttpServer.java
  engine/dlib/wscript
Labels: skip release notes

#7879 Make sure that we iterate over LU archive index only once
  engine/resource/src/providers/provider_zip.cpp
Labels: skip release notes

#7884 Turn signing for windows off
  editor/scripts/bundle.py
Labels: skip release notes

#7886 Make sure that TimeProfiler doesn't fail
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/TimeProfiler.java
Labels: skip release notes

#7891 Make sure we unmount archive when reboot or close application
  engine/resource/src/providers/provider_archive.cpp
  engine/resource/src/wscript
  scripts/unpack_ddf.py
Labels: skip release notes

#7892 Make fake bindings for missing attributes on Vulkan
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan_private.h
Labels: skip release notes

#7908 Property editor fixes
  editor/.idea/codeStyles/Project.xml
  editor/src/clj/editor/properties_view.clj
  editor/src/clj/editor/ui.clj
Labels: bug, editor

#7916 Calling go.get on a non-array constant property should give a single value
  engine/gameobject/src/gameobject/gameobject_script.cpp
  engine/gamesys/src/gamesys/test/material/material.go
  engine/gamesys/src/gamesys/test/material/material.script
  engine/gamesys/src/gamesys/test/material/material_constant_array.fp
  engine/gamesys/src/gamesys/test/material/material_constant_array.material
  engine/gamesys/src/gamesys/test/material/material_constant_single.fp
  engine/gamesys/src/gamesys/test/material/material_constant_single.material
  engine/gamesys/src/gamesys/test/material/material_generated_0.sprite
  engine/gamesys/src/gamesys/test/material/material_generated_1.sprite
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
Labels: skip release notes

#7894 Vulkan - Keep track of number of descriptors allocated from the pool
  engine/graphics/src/vulkan/android/graphics_vulkan_android.cpp
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan_device.cpp
  engine/graphics/src/vulkan/graphics_vulkan_dynamic.h
  engine/graphics/src/vulkan/graphics_vulkan_private.h
Labels: engine, vulkan, skip release notes

#7851 Delete sound instance if stopped before play issued
  engine/gamesys/src/gamesys/components/comp_sound.cpp
  engine/gamesys/src/gamesys/test/sound/delayed_sound_stopped_before_play.go
  engine/gamesys/src/gamesys/test/sound/delayed_sound_stopped_before_play.script
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
Labels: bug, engine, sound

#7924 Using transfer_ownership when updating buffers should incref the resource
  engine/gamesys/src/gamesys/scripts/script_resource.cpp
Labels: bug, engine

#7934 Less aggressive rounding of numeric values in the editor
  editor/src/clj/editor/field_expression.clj
  editor/src/clj/editor/gui.clj
  editor/src/clj/editor/math.clj
  editor/src/clj/editor/properties.clj
Labels: editor

#7932 Slightly improved editor scene view interactions for Guis with a lot of templates
  editor/project.clj
  editor/sidecar/aot.clj
  editor/src/clj/editor/gui.clj
  editor/src/clj/internal/graph.clj
  editor/src/clj/internal/node.clj
  editor/src/clj/internal/transaction.clj
  editor/src/dev/dev.clj
  editor/src/dev/prof.clj
  editor/src/dev/yourkit.clj
Labels: editor, gui, performance
