Repository defold/defold, pull requests merged in 2024-04, with the labels that each got.

#8748 Bugfix for vulkan, missing load+store ops for render targets
  engine/gamesys/src/gamesys/resources/res_render_target.cpp
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/render/src/render/render_script.cpp
Labels: skip release notes

#8734 Update `stb_image` to 2.29
  engine/dlib/src/stb/stb_image.h
Labels: skip release notes

#8751 Fixes misc inconsistencies when setting and getting custom vertex attributes by script
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/gamesys/src/gamesys/gamesys_private.cpp
  engine/gamesys/src/gamesys/gamesys_private.h
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
Labels: bug, engine

#8754 Editor: Support environment-variable replacement for usernames in dependency URLs
  editor/src/clj/editor/library.clj
  editor/src/dev/dev.clj
Labels: bug, editor

#8760 Update `builtins` materials
  engine/engine/content/builtins/materials/gui.material
  engine/engine/content/builtins/materials/model.material
  engine/engine/content/builtins/materials/particlefx.material
  engine/engine/content/builtins/materials/particlefx_paged_atlas.material
  engine/engine/content/builtins/materials/sprite.material
  engine/engine/content/builtins/materials/sprite_paged_atlas.material
  engine/engine/content/builtins/materials/tile_map.material
Labels: skip release notes

#8758 Add 'slice' as a property to get and set slice9 values
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/gamesys/src/gamesys/scripts/script_sprite.cpp
  engine/gamesys/src/gamesys/test/atlas/valid.atlas
  engine/gamesys/src/gamesys/test/sprite/sprite_slice9.go
  engine/gamesys/src/gamesys/test/sprite/sprite_slice9.script
  engine/gamesys/src/gamesys/test/sprite/sprite_slice9.sprite
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/gamesys/src/gamesys/test/test_gamesys.h
  engine/gamesys/src/gamesys/test/wscript
Labels: feature request, engine, sprite

#8757 Migrate texture fields to samplers
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/MaterialBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/MaterialBuilder.java
Labels: bug, bob

#8605 Added Linux layouts for 2 gamepads
  engine/engine/content/builtins/input/default.gamepads
Labels: skip release notes

#8769 Fixed broken gizmo manipulations for Model component
  editor/src/clj/editor/model_scene.clj
Labels: bug, editor

#8772 Added diff functions to the dev module
  editor/src/dev/dev.clj
Labels: task, editor, skip release notes

#8778 Use correct clang_rt for iOS simulator
  share/extender/build_input.yml
Labels: skip release notes

#8789 Added missing type to physics.set_shape() API examples
  engine/gamesys/src/gamesys/scripts/script_physics.cpp
Labels: skip release notes

#8788 Cleanup the defold sdk download from test libraries
  ci/ci.py
  engine/sdk/src/test/test_include.cpp
  engine/sdk/src/test/wscript
Labels: skip release notes

#8792 Move resource binding into shared location for all gfx adapters
  engine/graphics/src/graphics_private.h
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan_device.cpp
  engine/graphics/src/vulkan/graphics_vulkan_private.h
Labels: skip release notes

#8800 Allow for enabling/disabling the sprite slice9 at runtime
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
Labels: skip release notes

#8841 Fix b2d documentation
  editor/src/clj/editor/lua.clj
  engine/docs/src/script_doc.py
  engine/gamesys/src/gamesys/scripts/box2d/script_box2d.cpp
  engine/gamesys/src/gamesys/scripts/box2d/script_box2d_body.cpp
Labels: skip release notes

#8846 Fix build on macos-14-arm64
  scripts/build.py
Labels: skip release notes

#8851 Fix double-run web build in rare case.
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/resources/jsweb/dmloader.js
Labels: skip release notes

#8853 Support using no color when writing custom vertex attribute for sprites
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/graphics/src/graphics.cpp
  engine/graphics/src/graphics.h
Labels: bug, engine, graphics

#8866 Fix `get_linear_velocity_from_local_point` docs
  engine/gamesys/src/gamesys/scripts/box2d/script_box2d_body.cpp
Labels: skip release notes
