Repository defold/defold, pull requests merged in 2024-10, with the labels that each got.

#9510 Make the building artifacts independent for the `Build HTML5` and `Build` options
  editor/src/clj/editor/pipeline/bob.clj
  editor/src/clj/editor/workspace.clj
Labels: editor, html5

#9516 Remove INITIAL_HEAP compiler option.
  share/extender/build_input.yml
Labels: skip release notes

#9522 Consolidate writing attribute data from source "channels"
  engine/gamesys/src/gamesys/components/comp_model.cpp
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/graphics/src/graphics.h
  engine/graphics/src/graphics_vertices.cpp
  engine/graphics/src/test/test_graphics.cpp
  engine/particle/src/particle.cpp
  engine/rig/src/dmsdk/rig/rig.h
  engine/rig/src/rig.cpp
Labels: skip release notes

#9528 Change batch sorting based on if model is using instanced material or not
  engine/gamesys/src/gamesys/components/comp_model.cpp
Labels: skip release notes

#9524 Find the latest android.jar in the locally installed android studio
  build_tools/sdk.py
Labels: skip release notes

#9536 Fix wrong detection of a hash GO property
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/LuaScannerTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/LuaScanner.java
Labels: skip release notes

#9538 Configure default vertex attributes in the same way as the editor
  engine/gamesys/src/gamesys/components/comp_model.cpp
  engine/gamesys/src/gamesys/components/comp_particlefx.cpp
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/gamesys/src/gamesys/gamesys_private.cpp
  engine/gamesys/src/gamesys/gamesys_private.h
  engine/graphics/proto/graphics/graphics_ddf.proto
  engine/graphics/src/graphics_vertices.cpp
  engine/graphics/src/test/test_graphics.cpp
  engine/render/src/render/material.cpp
Labels: skip release notes

#9540 Editor: Added util.eduction module
  editor/src/clj/util/eduction.clj
  editor/test/util/eduction_test.clj
Labels: editor, skip release notes

#9543 Fix crash in profiler draw when the there is no current frame to render
  engine/profiler/src/profile_render.cpp
  engine/profiler/src/profile_render.h
Labels: skip release notes

#9561 Re-add missing glfw functionality for windows
  engine/graphics/src/graphics_glfw_wrappers.cpp
Labels: skip release notes

#9553 Make sure all the changes taken into account in the bundle
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Builder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/GameProjectBuilder.java
Labels: skip release notes

#9563 Only split combined samplers when needed
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderCompilePipelineTest.java
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderProgramBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderCompilers.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilderEditor.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderUtil.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/ShaderCompilePipeline.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/ShaderCompilePipelineLegacy.java
  editor/src/clj/editor/code/shader.clj
Labels: skip release notes

#9566 Add alpha blending before rendering profiler
  engine/profiler/src/profiler.cpp
Labels: bug, engine, profiler

#9574 External glfw now respect PREFIX variable. Fix glfw build.
  external/bullet3d/wscript
  external/glfw/wscript
Labels: skip release notes

#9567 Add vertex + index memory size to model profiling
  engine/gamesys/src/dmsdk/gamesys/resources/res_model.h
  engine/gamesys/src/gamesys/components/comp_model.cpp
  engine/graphics/src/graphics.cpp
  engine/graphics/src/graphics.h
  engine/graphics/src/graphics_adapter.h
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/opengl/graphics_opengl_private.h
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/webgpu/graphics_webgpu.cpp
Labels: engine, model, profiler

#9575 Provide info about file if graph creation failed
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/graph/ResourceWalker.java
Labels: skip release notes

#9490 allow selecting variant
  build_tools/waf_dynamo.py
  engine/engine/wscript
  scripts/build.py
  scripts/web/web-repack.sh
Labels: skip release notes

#9576 Remove Browser.destroyContext function usage
  external/glfw/js/library_glfw.js
  packages/glfw-2.7.1-js-web.tar.gz
  packages/glfw-2.7.1-wasm-web.tar.gz
Labels: skip release notes

#9555 Fix texture destroy in flight
  engine/gamesys/src/dmsdk/gamesys/resources/res_texture.h
  engine/gamesys/src/gamesys/resources/res_factory.cpp
  engine/gamesys/src/gamesys/resources/res_texture.cpp
Labels: skip release notes

#9589 Enable getting metal handles from vulkan via DMSDK
  engine/graphics/src/dmsdk/graphics/graphics_vulkan.h
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan_context.cpp
  engine/graphics/src/vulkan/graphics_vulkan_private.h
  engine/graphics/src/vulkan/osx/graphics_vulkan_osx.mm
  engine/graphics/src/wscript
Labels: skip release notes

#9550 Fix multi-materials in one skinning model
  engine/gamesys/src/gamesys/components/comp_model.cpp
Labels: bug, model, render

#9593 Cleanup state of the builders when build is done.
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Builder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/ProtoBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/CollectionBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/LuaBuilder.java
Labels: skip release notes

#9579 Add instanced model material to builtins
  engine/engine/content/builtins/materials/model_instanced.material
  engine/engine/content/builtins/materials/model_instanced.vp
Labels: feature request, engine, render

#9475 Http cache improvements
  editor/src/clj/editor/hot_reload.clj
  engine/dlib/src/dlib/configfile.cpp
  engine/dlib/src/dlib/http_cache_verify.cpp
  engine/dlib/src/dlib/http_client.cpp
  engine/dlib/src/dlib/http_client.h
  engine/dlib/src/test/test_httpclient.cpp
  engine/dlib/src/test/test_httpserver.cpp
  engine/gamesys/src/gamesys/test/http/http_request.script
  engine/resource/src/providers/provider_http.cpp
  engine/script/src/http_service.cpp
Labels: task, engine, editor

#9602 Fix issue with GUI particles not rendering
  engine/gamesys/src/gamesys/components/comp_gui.cpp
Labels: skip release notes

#9607 Fix for the new glyph cache
  engine/render/src/render/font_renderer.cpp
Labels: skip release notes

#9592 WebGPU issues
  engine/graphics/src/webgpu/graphics_webgpu.cpp
  engine/graphics/src/webgpu/graphics_webgpu_private.h
  engine/render/src/render/render.cpp
  share/extender/build_input.yml
Labels: skip release notes

#9636 Remove unused world constant from tile_map in builtins
  engine/engine/content/builtins/materials/tile_map.material
Labels: task, engine, graphics, render

#9654 Use a global vao when enabling a vertex declaration
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/opengl/graphics_opengl_private.h
Labels: skip release notes

#9659 Misc platform fixes for extensions
  engine/graphics/src/dmsdk/graphics/graphics_opengl.h
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/wscript
  external/glfw/lib/ios/app/VulkanView.m
  packages/glfw-2.7.1-arm64-ios.tar.gz
Labels: feature request, engine, vulkan, opengl, dmsdk

#9660 Configure opengl context creation
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/meta.properties
  editor/resources/meta.edn
  editor/test/resources/save_data_project/game.project
  engine/engine/src/engine.cpp
  engine/platform/src/platform_window.h
  engine/platform/src/platform_window_glfw.cpp
  engine/platform/src/platform_window_glfw3.cpp
  engine/platform/src/platform_window_opengl.h
Labels: engine, opengl

#9643 Fix crash when MaxDynamicTextures == 0.
  engine/gui/src/gui.cpp
  engine/gui/src/test/test_gui.cpp
Labels: bug

#9637 Proper engine shutdown
  editor/src/clj/editor/console.clj
  engine/engine/src/engine.cpp
  engine/gameobject/src/gameobject/gameobject.cpp
  engine/hid/src/native/hid_native.cpp
  engine/resource/src/resource_type.cpp
Labels: engine, editor, skip release notes

#9629 Add webgpu entries to manifest tool
  com.dynamo.cr/com.dynamo.cr.bob/build.gradle
  com.dynamo.cr/com.dynamo.cr.bob/scripts/copy.sh
  editor/src/clj/editor/app_manifest.clj
  editor/tasks/leiningen/pack.clj
  editor/test/integration/app_manifest_test.clj
  editor/test/resources/test_project/app_manifest/webgpu.appmanifest
  editor/test/resources/test_project/app_manifest/webgpu_and_webgl.appmanifest
  packages/tint-22b958-x86_64-win32.tar.gz
  scripts/build.py
Labels: editor, html5, webgpu

#9669 Set OpenGL version from editor cosmetic addendum
  editor/resources/meta.edn
Labels: skip release notes

#9642 Move common settings to common platform description
  share/extender/build_input.yml
Labels: skip release notes
