Repository defold/defold, pull requests merged in 2024-11, with the labels that each got.

#9694 Luajit retry if it crashes
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/AtlasBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/CubemapBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/LuaBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/TextureBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/TileSetBuilder.java
Labels: skip release notes

#9693 move_script: copy object before update redirect.
  build_tools/s3.py
Labels: skip release notes

#9698 Fix default log level: it should be User Debug to be able to see prints from Lua by default
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/meta.properties
  editor/resources/meta.edn
  editor/test/resources/save_data_project/game.project
Labels: skip release notes

#9705 Use old mapping for mouse buttons
  engine/hid/src/dmsdk/hid/glfw/hid_native_defines.h
Labels: skip release notes

#9691 Detect DMFS (meant to operate like IDBFS or NODEFS) as a replacement …
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/resources/jsweb/dmloader.js
Labels: feature request, engine, html5

#9706 Strip clrf line endings from shader source
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderProgramBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilder.java
Labels: bug, engine

#9725 Setting 'highest available' opengl ctx is not supported on osx
  engine/platform/src/platform_window_opengl.h
  engine/tools/src/gdc/main.cpp
Labels: bug, engine, glfw

#9456 Added Wasapi sound backend for Windows
  build_tools/BuildUtility.py
  build_tools/waf_dynamo.py
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/bundle/test/BundlerTest.java
  com.dynamo.cr/com.dynamo.cr.bob/build.gradle
  com.dynamo.cr/com.dynamo.cr.bob/scripts/copy.sh
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/Win32Bundler.java
  editor/src/clj/editor/engine.clj
  engine/engine/src/wscript
  engine/engine/wscript
  engine/jni/src/test/wscript
  engine/sound/README.md
  engine/sound/src/decoders/decoder_wav.cpp
  engine/sound/src/devices/device_js.cpp
  engine/sound/src/devices/device_null.cpp
  engine/sound/src/devices/device_openal.cpp
  engine/sound/src/devices/device_opensl.cpp
  engine/sound/src/devices/device_wasapi.cpp
  engine/sound/src/sound.cpp
  engine/sound/src/sound.h
  engine/sound/src/test/test_sound.cpp
  engine/sound/src/test/test_sound_null.cpp
  engine/sound/src/test/wscript
  engine/sound/src/wscript
  packages/openal-1.1-win32.tar.gz
  packages/openal-1.1-x86_64-win32.tar.gz
  scripts/build.py
  share/extender/build_input.yml
Labels: sound, windows

#9730 Enable instanced arrays on WebGL 1.0
  engine/graphics/src/opengl/graphics_opengl.cpp
Labels: task, engine, graphics, opengl

#9756 Fix regex in build_input.yml
  share/extender/build_input.yml
Labels: skip release notes

#9758 Added missed library for new windows sound backend.
  share/extender/build_input.yml
Labels: skip release notes

#9784 Set clearcolor alpha to one by default
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/meta.properties
  editor/resources/meta.edn
Labels: bug, engine, editor, bob, render

#9792 Use actual dpi value in glfw get display scale factor
  external/glfw/js/library_glfw.js
  packages/glfw-2.7.1-js-web.tar.gz
  packages/glfw-2.7.1-wasm-web.tar.gz
Labels: bug, engine, glfw

#9807 Update Android build commands.
  share/extender/build_input.yml
Labels: skip release notes

#9809 Editor: Add memory and graph inspection functions to the dev module
  editor/.idea/codeStyles/Project.xml
  editor/project.clj
  editor/src/clj/editor/code/syntax.clj
  editor/src/clj/editor/defold_project.clj
  editor/src/clj/editor/texture_set.clj
  editor/src/clj/util/coll.clj
  editor/src/clj/util/debug_util.clj
  editor/src/clj/util/eduction.clj
  editor/src/clj/util/fn.clj
  editor/src/dev/dev.clj
  editor/src/dev/load_project.clj
  editor/src/dev/mem.clj
  editor/test/editor/analytics_test.clj
  editor/test/editor/code/util_test.clj
  editor/test/editor/defold_project_search_test.clj
  editor/test/editor/handler_test.clj
  editor/test/editor/sync_test.clj
  editor/test/editor/targets_test.clj
  editor/test/integration/build_errors_test.clj
  editor/test/integration/label_test.clj
  editor/test/integration/test_util.clj
  editor/test/internal/util_test.clj
  editor/test/util/coll_test.clj
  editor/test/util/eduction_test.clj
  editor/test/util/fn_test.clj
Labels: editor, skip release notes, performance, memory

#9783 Don't use material after release
  engine/gamesys/src/gamesys/components/comp_mesh.cpp
Labels: bug, engine, mesh

#9814 Copy shader tools once to avoid issues in threaded builds
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/ShaderCompilePipeline.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/ShaderCompilePipelineLegacy.java
Labels: skip release notes

#9815 ParticleFx vertex buffer batch update
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/meta.properties
  editor/resources/meta.edn
  editor/test/resources/save_data_project/game.project
  engine/gamesys/src/gamesys/components/comp_particlefx.cpp
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/gamesys/src/gamesys/test/test_gamesys.h
  engine/particle/src/particle.cpp
  engine/particle/src/particle.h
  engine/particle/src/particle_private.h
  engine/particle/src/test/test_particle.cpp
Labels: engine, particlefx, performance

#9808 Update Extender's client to the latest version.
  com.dynamo.cr/com.dynamo.cr.common/ext/extender-client-0.0.5.jar
  com.dynamo.cr/com.dynamo.cr.common/ext/extender-client-0.1.0.jar
Labels: skip release notes

#9806 Hotfix for max_instances counter in case of models/rive/spine components
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/ComponentsCounter.java
Labels: skip release notes

#9832 Setup instruction fixes.
  README_SETUP.md
Labels: skip release notes

#9830 Shaderc library based on spirv cross
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderCompilePipelineTest.java
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderProgramBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob.test/test/simple.spv
  com.dynamo.cr/com.dynamo.cr.bob/.gitignore
  com.dynamo.cr/com.dynamo.cr.bob/build.gradle
  com.dynamo.cr/com.dynamo.cr.bob/scripts/copy.sh
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderCompilers.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/SPIRVReflector.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/ShaderCompilePipeline.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/ShaderCompilePipelineLegacy.java
  editor/tasks/leiningen/pack.clj
  engine/shaderc/src/java/com/dynamo/bob/pipeline/Shaderc.java
  engine/shaderc/src/java/com/dynamo/bob/pipeline/ShadercJni.java
  engine/shaderc/src/jni/Shaderc_jni.cpp
  engine/shaderc/src/jni/Shaderc_jni.h
  engine/shaderc/src/shaderc.cpp
  engine/shaderc/src/shaderc.h
  engine/shaderc/src/shaderc_jni.cpp
  engine/shaderc/src/test/data/bindings.vert
  engine/shaderc/src/test/data/legacy_pipeline.frag
  engine/shaderc/src/test/data/reflection.frag
  engine/shaderc/src/test/data/simple.frag
  engine/shaderc/src/test/data/ssbo.frag
  engine/shaderc/src/test/data/structs.frag
  engine/shaderc/src/test/data/types.frag
  engine/shaderc/src/test/test_shaderc.cpp
  engine/shaderc/src/test/wscript
  engine/shaderc/src/wscript
  engine/shaderc/wscript
  packages/spirv-cross-197a273f-arm64-macos.tar.gz
  packages/spirv-cross-197a273f-x86_64-linux.tar.gz
  packages/spirv-cross-197a273f-x86_64-macos.tar.gz
  packages/spirv-cross-37fee00a-arm64-linux.tar.gz
  packages/spirv-cross-9040e0d2-arm64-linux.tar.gz
  packages/spirv-cross-9040e0d2-arm64-macos.tar.gz
  packages/spirv-cross-9040e0d2-x86_64-linux.tar.gz
  packages/spirv-cross-9040e0d2-x86_64-macos.tar.gz
  packages/spirv-cross-9040e0d2-x86_64-win32.tar.gz
  packages/spirv-cross-dae7a689-arm64-macos.tar.gz
  packages/spirv-cross-dae7a689-x86_64-macos.tar.gz
  packages/spirv-cross-edd66a2f-x86_64-linux.tar.gz
  packages/spirv-cross-edd66a2f-x86_64-macos.tar.gz
  packages/spirv-cross-edd66a2f-x86_64-win32.tar.gz
  scripts/build.py
  share/ext/spirv-cross/build_spirv-cross.sh
Labels: task, engine, shader
