Repository defold/defold, pull requests merged in 2024-02, with the labels that each got.

#8487 Fix `physics.set_listener()` callback. Use hash intead of string.
  engine/gamesys/src/gamesys/scripts/script_physics.cpp
  engine/gamesys/src/gamesys/test/collision_object/callback_object.script
Labels: skip release notes

#8476 Use a shared dmJobThread worker for gamesys and graphics
  apply_license.py
  engine/dlib/src/dlib/job_thread.cpp
  engine/dlib/src/dlib/job_thread.h
  engine/dlib/src/dlib/thread.h
  engine/dlib/src/jc/ringbuffer.h
  engine/dlib/src/test/test_job_thread.cpp
  engine/dlib/src/test/wscript
  engine/dlib/src/wscript
  engine/engine/src/engine.cpp
  engine/engine/src/engine_private.h
  engine/gamesys/src/gamesys/gamesys.h
  engine/gamesys/src/gamesys/gamesys_private.cpp
  engine/gamesys/src/gamesys/resources/res_texture.h
  engine/gamesys/src/gamesys/scripts/script_resource.cpp
  engine/gamesys/src/gamesys/scripts/script_sys_gamesys.cpp
  engine/gamesys/src/gamesys/test/sys/load_buffer_async.script
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/graphics/src/graphics.cpp
  engine/graphics/src/graphics.h
  engine/graphics/src/graphics_private.h
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/null/graphics_null_private.h
  engine/graphics/src/opengl/async/job_queue.h
  engine/graphics/src/opengl/async/job_queue_sync.cpp
  engine/graphics/src/opengl/async/job_queue_threaded.cpp
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/opengl/graphics_opengl_private.h
  engine/graphics/src/test/test_graphics.cpp
  engine/graphics/src/wscript
  engine/liveupdate/src/liveupdate.cpp
  engine/liveupdate/src/test/test_liveupdate_job.cpp
  engine/platform/src/platform_window.h
  engine/platform/src/platform_window_glfw.cpp
  engine/resource/src/async/load_queue.h
  engine/resource/src/async/load_queue_sync.cpp
  engine/resource/src/async/load_queue_threaded.cpp
  engine/resource/src/resource.h
  engine/resource/src/resource_private.h
  engine/resource/src/wscript
Labels: skip release notes

#8491 Fix graphics tests due to threading changes
  engine/dlib/src/dlib/thread_posix.cpp
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/test/test_graphics.cpp
Labels: skip release notes

#8500 Prevent crash when creating a joint in callback
  engine/gamesys/src/gamesys/components/comp_collision_object.cpp
  engine/gamesys/src/gamesys/scripts/script_physics.cpp
  engine/physics/src/physics/physics.h
  engine/physics/src/physics/physics_2d.cpp
  engine/physics/src/physics/physics_2d_null.cpp
Labels: skip release notes

#8497 Vertex declaration simplifcation
  engine/graphics/src/dmsdk/graphics/graphics.h
  engine/graphics/src/graphics.cpp
  engine/graphics/src/graphics_adapter.h
  engine/graphics/src/graphics_private.h
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/null/graphics_null_private.h
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/opengl/graphics_opengl_private.h
  engine/graphics/src/test/test_graphics.cpp
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan.h
  engine/graphics/src/vulkan/graphics_vulkan_device.cpp
  engine/graphics/src/vulkan/graphics_vulkan_private.h
  engine/render/src/test/test_render.cpp
Labels: skip release notes

#8506 Use default `android_native_app_glue.c` instead of custom one
  README_ANDROID.md
  build_tools/waf_dynamo.py
  external/glfw/lib/android/android_native_app_glue.c
  external/glfw/lib/android/android_window.c
  packages/glfw-2.7.1-arm64-android.tar.gz
  packages/glfw-2.7.1-armv7-android.tar.gz
Labels: android, skip release notes

#8514 Fix thread memory read/write issues
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/test/test_graphics.cpp
Labels: skip release notes

#8484 Fix multi-buffered render buffers on non-opengl graphics adapters
  engine/gamesys/src/gamesys/components/comp_model.cpp
  engine/gamesys/src/gamesys/components/comp_particlefx.cpp
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/gamesys/src/gamesys/components/comp_tilegrid.cpp
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/dispatch_buffers_test.go
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/material_a.material
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/material_b.material
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/model_material_a.model
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/model_material_b.model
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/particlefx.tilesource
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/particlefx_a.particlefx
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/particlefx_b.particlefx
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/quad_2x2.prebuilt_animationsetc
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/quad_2x2.prebuilt_meshsetc
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/quad_2x2.prebuilt_skeletonc
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/sprite_material_a.sprite
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/sprite_material_b.sprite
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/tilegrid_a.tilegrid
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/vs_format_a.vp
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/vs_format_b.vp
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/gamesys/src/gamesys/test/test_gamesys.h
  engine/gamesys/src/gamesys/test/wscript
Labels: bug

#8517 Update the path hash for the luabuffer when transferring ownership
  engine/gamesys/src/gamesys/scripts/script_resource.cpp
Labels: skip release notes

#8424 Render target as a resource
  com.dynamo.cr/com.dynamo.cr.bob.test/build.xml
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ParseUtil.java
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/RenderPrototypeBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/build.xml
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ProtoBuilders.java
  editor/resources/templates/template.render_target
  editor/src/clj/editor/code/script.clj
  editor/src/clj/editor/mesh.clj
  editor/src/clj/editor/model.clj
  editor/src/clj/editor/render_pb.clj
  editor/src/clj/editor/render_target.clj
  editor/src/clj/editor/resource.clj
  editor/src/clj/editor/resource_types.clj
  editor/test/integration/save_data_test.clj
  editor/test/integration/script_properties_test.clj
  editor/test/integration/test_util.clj
  editor/test/resources/save_data_project/checked.render
  editor/test/resources/save_data_project/checked.render_target
  editor/test/resources/save_data_project/silently_migrated/legacy_render_prototype.render
  engine/gamesys/src/dmsdk/gamesys/resources/res_mesh.h
  engine/gamesys/src/dmsdk/gamesys/resources/res_model.h
  engine/gamesys/src/dmsdk/gamesys/resources/res_texture.h
  engine/gamesys/src/gamesys/components/comp_mesh.cpp
  engine/gamesys/src/gamesys/components/comp_model.cpp
  engine/gamesys/src/gamesys/gamesys.cpp
  engine/gamesys/src/gamesys/gamesys.h
  engine/gamesys/src/gamesys/gamesys_private.cpp
  engine/gamesys/src/gamesys/gamesys_private.h
  engine/gamesys/src/gamesys/resources/res_mesh.cpp
  engine/gamesys/src/gamesys/resources/res_model.cpp
  engine/gamesys/src/gamesys/resources/res_render_prototype.cpp
  engine/gamesys/src/gamesys/resources/res_render_target.cpp
  engine/gamesys/src/gamesys/resources/res_render_target.h
  engine/gamesys/src/gamesys/resources/res_texture.cpp
  engine/gamesys/src/gamesys/resources/res_texture.h
  engine/gamesys/src/gamesys/scripts/script_resource.cpp
  engine/gamesys/src/gamesys/test/render/resources.render
  engine/gamesys/src/gamesys/test/render_target/render_target.model
  engine/gamesys/src/gamesys/test/render_target/valid.render_target
  engine/gamesys/src/gamesys/test/resource/script_render_target.go
  engine/gamesys/src/gamesys/test/resource/script_render_target.script
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/gamesys/src/gamesys/test/wscript
  engine/gamesys/src/waf_gamesys.py
  engine/graphics/proto/graphics/graphics_ddf.proto
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/render/proto/render/render_ddf.proto
  engine/render/proto/render/render_target_ddf.proto
  engine/render/src/render/render.h
  engine/render/src/render/render_script.cpp
  engine/render/src/render/render_script.h
  engine/render/src/test/test_render_script.cpp
  scripts/unpack_ddf.py
Labels: feature request, render

#8527 Beta test bugfixes
  engine/gamesys/src/dmsdk/gamesys/script.h
  engine/gamesys/src/gamesys/scripts/script_buffer.cpp
  engine/gamesys/src/gamesys/scripts/script_buffer.h
  engine/gamesys/src/gamesys/scripts/script_resource.cpp
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/fs_shared.fp
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/material_a.material
  engine/gamesys/src/gamesys/test/misc/dispatch_buffers_test/material_b.material
  engine/gamesys/src/gamesys/test/resource/script_buffer.script
Labels: skip release notes

#8523 Fix issues with 'physics.set(get)_shape()` for box2d
  engine/gamesys/src/gamesys/components/comp_collision_object.cpp
  engine/gamesys/src/gamesys/test/collision_object/get_set_shape.collisionobject
  engine/gamesys/src/gamesys/test/collision_object/get_set_shape.script
  engine/physics/src/physics/physics.h
  engine/physics/src/physics/physics_2d.cpp
  engine/physics/src/physics/physics_2d.h
  engine/physics/src/physics/physics_2d_null.cpp
Labels: physics, skip release notes

#8530 Pass HMaterial handle and not resource handle to render prototype
  engine/gamesys/src/gamesys/resources/res_render_prototype.cpp
Labels: skip release notes

#8532 Notify in Slack about job fail only for `dev`, `beta` and `master`
  .github/workflows/main-ci.yml
Labels: skip release notes

#8522 Graph successor memory optimizations
  editor/project.clj
  editor/src/clj/internal/graph.clj
  editor/src/clj/internal/node.clj
  editor/src/dev/mem.clj
Labels: editor

#8553 Removed old deprecated messages
  engine/gameobject/proto/gameobject/gameobject_ddf.proto
  engine/gameobject/src/gameobject/gameobject.cpp
  engine/gameobject/src/gameobject/gameobject_script.cpp
  engine/gameobject/src/gameobject/test/message/test_gameobject_message.cpp
  engine/gamesys/proto/gamesys/tile_ddf.proto
  engine/gamesys/src/gamesys/components/comp_tilegrid.cpp
Labels: breaking change

#8538 Do not add extra new line if there is one exist
  engine/crash/src/crash.cpp
Labels: skip release notes

#8575 Add linking with IOSurface when bundling for vulkan on iOS
  editor/src/clj/editor/app_manifest.clj
  editor/test/resources/test_project/app_manifest/vulkan.appmanifest
  editor/test/resources/test_project/app_manifest/vulkan_and_opengl.appmanifest
Labels: skip release notes

#8559 Removed `system_font.font` from `builtins`
  editor/resources/templates/template.label
  editor/src/clj/editor/gui.clj
  editor/test/integration/build_test.clj
  editor/test/integration/gui_test.clj
  editor/test/resources/build_project/SideScroller/main/label.label
  editor/test/resources/label_migration_project/scale_migration/embedded_scaled_label.collection
  editor/test/resources/label_migration_project/scale_migration/embedded_scaled_label.go
  editor/test/resources/label_migration_project/scale_migration/embedded_scaled_label_child.collection
  editor/test/resources/label_migration_project/scale_migration/scaled_label.label
  editor/test/resources/label_migration_project/scale_migration/unscaled_label.label
  editor/test/resources/override_project/main/button2.gui
  editor/test/resources/override_project/main/child.gui
  editor/test/resources/override_project/main/grandchild.gui
  editor/test/resources/override_project/main/hud.gui
  editor/test/resources/override_project/main/panel2.gui
  editor/test/resources/override_project/main/parent.gui
  editor/test/resources/reload_project/gui/scene.gui
  editor/test/resources/reload_project/label/label.label
  editor/test/resources/reload_project/label/new_label.label
  editor/test/resources/test_project/collection/all_embedded.collection
  editor/test/resources/test_project/collection/components/test.label
  editor/test/resources/test_project/gui/empty.gui
  editor/test/resources/test_project/gui/layers.gui
  editor/test/resources/test_project/gui/legacy_alpha.gui
  editor/test/resources/test_project/gui/scene.gui
  editor/test/resources/test_project/gui/simple.gui
  editor/test/resources/test_project/gui/sub_scene.gui
  editor/test/resources/test_project/gui/super_scene.gui
  editor/test/resources/test_project/gui_resources/gui_resources.gui
  editor/test/resources/test_project/gui_resources/replaces_broken_gui_resources.gui
  editor/test/resources/test_project/gui_resources/replaces_gui_resources.gui
  editor/test/resources/test_project/label/embedded_label.collection
  editor/test/resources/test_project/label/embedded_label.go
  editor/test/resources/test_project/label/test.label
  engine/engine/content/builtins/fonts/debug/always_on_top.font
  engine/engine/content/builtins/fonts/debug/always_on_top_font.material
  engine/engine/content/builtins/fonts/default.font
  engine/engine/content/builtins/render/default.render_script
  engine/engine/content/wscript
  engine/engine/src/engine.cpp
  engine/engine/src/test/def-3575/def-3575-bitmap.font
  engine/engine/src/test/def-3575/def-3575-df.font
  engine/engine/src/test/label/label.font
  engine/engine/src/test/loading/loading.gui
  engine/engine/src/test/script_props/gui/prop_gui.gui
  engine/engine/src/test/script_props/gui/prop_gui.script
  engine/engine/src/test/script_props/gui/system_font.font
  engine/engine/src/test/script_props/gui/system_font_big.font
Labels: breaking change

#8552 Support sampler names in render.enable_texture
  engine/graphics/src/null/glsl_uniform_parser.cpp
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/null/graphics_null_private.h
  engine/render/src/render/material.cpp
  engine/render/src/render/render.cpp
  engine/render/src/render/render_command.cpp
  engine/render/src/render/render_private.h
  engine/render/src/render/render_script.cpp
  engine/render/src/test/test_render.cpp
  engine/render/src/test/test_render_script.cpp
Labels: engine, graphics

#8574 Move spirv generation to shared bob/editor location
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Bob.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java
Labels: skip release notes

#8569 Added support for sprite to not have a texture assigned
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ProtoBuilders.java
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/gamesys/src/gamesys/resources/res_sprite.cpp
Labels: engine, sprite

#8548 Removed deprecated extensions from the code
  README_DOCS.md
  README_ENGINE.md
  build_tools/waf_dynamo.py
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/meta.properties
  editor/resources/meta.edn
  editor/src/clj/editor/lua.clj
  engine/engine/content/builtins/docs/facebook.md
  engine/engine/content/builtins/docs/iac.md
  engine/engine/content/builtins/docs/iap.md
  engine/engine/content/builtins/docs/push.md
  engine/engine/content/builtins/docs/webview.md
  engine/engine/src/wscript
  engine/engine/wscript
  engine/facebook/src/facebook_doc.h
  engine/facebook/src/facebook_null.cpp
  engine/facebook/src/facebook_stub.cpp
  engine/facebook/src/wscript
  engine/facebook/wscript
  engine/iac/README.md
  engine/iac/src/iac_doc.h
  engine/iac/src/iac_null.cpp
  engine/iac/src/iac_stub.cpp
  engine/iac/src/wscript
  engine/iac/wscript
  engine/iap/src/iap_doc.h
  engine/iap/src/iap_null.cpp
  engine/iap/src/iap_stub.cpp
  engine/iap/src/wscript
  engine/iap/wscript
  engine/push/README.md
  engine/push/src/push_doc.h
  engine/push/src/push_null.cpp
  engine/push/src/push_stub.cpp
  engine/push/src/wscript
  engine/push/wscript
  engine/script/src/test/test_script_lua.cpp
  engine/webview/src/webview_doc.h
  engine/webview/src/webview_mobile.cpp
  engine/webview/src/webview_null.cpp
  engine/webview/src/wscript
  engine/webview/wscript
  scripts/build.py
  share/extender/build_input.yml
Labels: breaking change

#8572 Add an ability to use DM_BOB_BUNDLERTEST_ONLY_HOST in IDEA
  com.dynamo.cr/com.dynamo.cr.bob.test/build.xml
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/bundle/test/BundlerTest.java
Labels: skip release notes

#8562 Set custom vertex data API (Sprites)
  engine/gamesys/src/gamesys/components/comp_model.cpp
  engine/gamesys/src/gamesys/components/comp_particlefx.cpp
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/gamesys/src/gamesys/gamesys_private.cpp
  engine/gamesys/src/gamesys/gamesys_private.h
  engine/gamesys/src/gamesys/test/material/attributes_dynamic.material
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/render/src/render/material.cpp
  engine/render/src/render/program_utils.cpp
  engine/render/src/render/render.h
  engine/render/src/render/render_private.h
  engine/render/src/test/test_material.cpp
Labels: feature request, engine

#8528 More options for min filter in `game.project`->`Graphics`->`Default Texture Min Filter`
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/meta.properties
  editor/resources/meta.edn
  editor/src/clj/editor/defold_project.clj
  editor/src/clj/editor/gl/texture.clj
  engine/engine/src/engine.cpp
  engine/graphics/src/opengl/graphics_opengl.cpp
Labels: breaking change

#8582 Crash fixes for the GDC tool
  engine/hid/src/native/hid_native.cpp
  engine/tools/src/gdc/main.cpp
Labels: engine

#8583 Use correct material tag for mesh components
  engine/gamesys/src/gamesys/components/comp_mesh.cpp
Labels: bug, engine

#8586 Instruction on how to build and run bob in IDEA + Ant job fixes
  com.dynamo.cr/README.md
  com.dynamo.cr/com.dynamo.cr.bob/README.md
  com.dynamo.cr/com.dynamo.cr.bob/build.xml
  com.dynamo.cr/com.dynamo.cr.common/build.xml
Labels: skip release notes

#8593 Paged atlas preview bugfix
  editor/src/clj/editor/graphics.clj
Labels: skip release notes

#8577 Add support for enabling a render target resource in render.enable_texture
  engine/graphics/src/null/graphics_null_private.h
  engine/render/src/render/render_script.cpp
  engine/render/src/test/test_render_script.cpp
Labels: feature request, engine, render

#8599 Flip image flag for image.load
  engine/dlib/src/dlib/image.cpp
  engine/dlib/src/dlib/image.h
  engine/dlib/src/test/test_image.cpp
  engine/gamesys/src/gamesys/scripts/script_image.cpp
  engine/gamesys/src/gamesys/test/image/test_image_buffer.script
Labels: feature request, engine

#8591 Add `retry_count` and `retry_time` settings to the `game.project` file in the `html5` section.
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/meta.properties
  editor/resources/meta.edn
  editor/test/resources/save_data_project/game.project
  engine/engine/content/builtins/manifests/web/engine_template.html
Labels: html5

#8576 Improved apis for adding custom atlas formats
  .gitignore
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/AtlasBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/textureset/test/TextureSetLayoutTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/defold/util/IDigestable.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/AtlasBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/AtlasUtil.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/CubemapBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/GuiBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/LuaBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ProtoBuilders.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/TextureGenerator.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/plugin/IPlugin.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/textureset/MaxRectsLayoutStrategy.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/textureset/TextureSetGenerator.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/textureset/TextureSetLayout.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/tile/TileSetUtil.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/PropertiesUtil.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/TextureUtil.java
  editor/src/clj/editor/atlas.clj
  editor/src/clj/editor/code/script.clj
  editor/src/clj/editor/graphics.clj
  editor/src/clj/editor/gui.clj
  editor/src/clj/editor/pipeline/tex_gen.clj
  editor/src/clj/editor/pipeline/texture_set_gen.clj
  editor/src/clj/editor/sprite.clj
  editor/src/clj/editor/texture_set.clj
  editor/src/clj/editor/tile_source.clj
  editor/src/clj/editor/workspace.clj
  editor/src/clj/util/digestable.clj
  editor/test/integration/script_properties_test.clj
  editor/test/util/digestable_test.clj
  engine/engine/content/builtins/materials/sprite_paged_atlas.material
  engine/gamesys/proto/gamesys/texture_set_ddf.proto
  engine/gamesys/proto/gamesys/tile_ddf.proto
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/gamesys/src/gamesys/resources/res_textureset.cpp
  engine/graphics/src/graphics_adapter.h
Labels: editor, bob, atlas

#8601 Use arm64 dart-sass on Apple silicon
  editor/tasks/leiningen/sass.clj
Labels: editor, skip release notes
