Repository defold/defold, pull requests merged in 2024-05, with the labels that each got.

#8875 Remove Logitech Gamepad F310 duplicate for linux
  engine/engine/content/builtins/input/default.gamepads
Labels: skip release notes

#8882 Support building a mesh without any samplers assigned
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/MeshBuilder.java
Labels: bug, engine

#8893 Engine crashes when producing secondary uv sets
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
Labels: bug, engine, sprite, graphics

#8867 Added bitcode_strip to build_input.yml
  share/extender/build_input.yml
Labels: skip release notes

#8889 Fix move_release logic. Miss copy object step.
  build_tools/s3.py
Labels: skip release notes

#8870 Add error reason for fwrite in sys.save
  engine/script/src/script_sys.cpp
Labels: task, feature request, engine

#8897 Produce SPIR-v shaders automatically on windows
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java
Labels: skip release notes

#8898 Improve dmloader error handling.
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/resources/jsweb/dmloader.js
Labels: skip release notes

#8901 In gitattributes, use Protocol Buffer Text Format language classifier instead of JSON5
  .gitattributes
Labels: skip release notes

#8864 Added missing lua_source_ddf.proto to dmSDK
  engine/script/src/wscript
Labels: bug, engine, dmsdk

#8917 Clarify use of collectionproxy.get_resources()
  engine/gamesys/src/gamesys/components/comp_collection_proxy.cpp
Labels: skip release notes

#8920 Properly fixed overrides in gitattribute for protobuffer text files
  .gitattributes
Labels: skip release notes

#8913 Update release notes
  RELEASE.md
  scripts/releasenotes_git.py
Labels: skip release notes

#8938 Make sure animation properties initialized properly
  engine/gameobject/src/dmsdk/gameobject/gameobject.h
  engine/gameobject/src/gameobject/gameobject.cpp
Labels: skip release notes

#8943 Don't override textures that have no matching sampler in material
  engine/render/src/render/render.cpp
Labels: skip release notes

#8944 Triple the timeout value in the async buffer tests
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
Labels: skip release notes

#8954 Remove bullet libs that somehow got included in glfw packages
  packages/glfw-2.7.1-arm64-android.tar.gz
  packages/glfw-2.7.1-x86_64-linux.tar.gz
Labels: skip release notes

#8945 Use resource pointers all the way for GUI textures
  engine/gamesys/src/gamesys/components/comp_gui.cpp
  engine/gamesys/src/gamesys/test/gui/texture_resources/texture_resources.go
  engine/gamesys/src/gamesys/test/gui/texture_resources/texture_resources.gui
  engine/gamesys/src/gamesys/test/gui/texture_resources/texture_resources.gui_script
  engine/gamesys/src/gamesys/test/gui/texture_resources/texture_resources.script
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/gamesys/src/gamesys/test/test_gamesys.h
  engine/gamesys/src/gamesys/test/wscript
Labels: skip release notes

#8942 Editor: Unversion vcs.xml from .idea since it contains local settings
  editor/.idea/.gitignore
  editor/.idea/vcs.xml
Labels: editor, skip release notes

#8939 Add extension-teal tests to the editor
  editor/.idea/codeStyles/Project.xml
  editor/project.clj
  editor/src/clj/dynamo/graph.clj
  editor/src/clj/editor/buffer.clj
  editor/src/clj/editor/code/resource.clj
  editor/src/clj/editor/code/script.clj
  editor/src/clj/editor/code/script_compilation.clj
  editor/src/clj/editor/code/shader.clj
  editor/src/clj/editor/code/transpilers.clj
  editor/src/clj/editor/defold_project.clj
  editor/src/clj/editor/fs.clj
  editor/src/clj/editor/library.clj
  editor/src/clj/editor/protobuf.clj
  editor/src/clj/editor/resource.clj
  editor/src/clj/editor/resource_node.clj
  editor/src/clj/editor/settings_core.clj
  editor/test/integration/extension_lua_preprocessor_test.clj
  editor/test/integration/extension_spine_test.clj
  editor/test/integration/extension_teal_test.clj
  editor/test/integration/extension_transpilers_test.clj
  editor/test/integration/test_util.clj
  editor/test/internal/graph/graph_test.clj
  editor/test/resources/save_data_project/game.project
  editor/test/resources/transpile_teal_project/.gitattributes
  editor/test/resources/transpile_teal_project/.gitignore
  editor/test/resources/transpile_teal_project/game.project
  editor/test/resources/transpile_teal_project/main/main.collection
  editor/test/resources/transpile_teal_project/main/main.script
  editor/test/resources/transpile_teal_project/modules/mathutils.tl
  editor/test/resources/transpile_teal_project/modules/textutils.tl
  editor/test/resources/transpile_teal_project/modules/vector.tl
  editor/test/resources/transpile_teal_project/tlconfig.lua
  editor/test/resources/transpilers_project/main/main.script
  editor/test/resources/transpilers_project/modules/main.tl
Labels: skip release notes

#8961 Fix failing engine tests
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
Labels: skip release notes

#8972 Fix crash in GUI when atlas changes texture resource internally
  engine/gamesys/src/dmsdk/gamesys/resources/res_gui.h
  engine/gamesys/src/gamesys/components/comp_gui.cpp
  engine/gamesys/src/gamesys/resources/res_gui.cpp
Labels: bug, engine, gui

#8976 Added optionality for `sys.reboot` arguments
  engine/script/src/script_sys.cpp
Labels: skip release notes

#8980 Added the ability to select a tile region in the palette map as a brush
  editor/src/clj/editor/tile_map.clj
Labels: editor, tilemap

#8993 Fix for input key disparity between glfw and glfw3
  engine/hid/src/hid.cpp
  engine/hid/src/native/hid_native.cpp
  engine/platform/src/platform_window_constants.h
  engine/platform/src/platform_window_glfw.cpp
  engine/platform/src/platform_window_glfw3.cpp
  engine/platform/src/platform_window_null.cpp
Labels: skip release notes

#9000 Always set number of touches
  engine/hid/src/hid.cpp
  engine/hid/src/native/hid_native.cpp
Labels: skip release notes

#9003 Fix MaxRectsLayout calculations
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/textureset/MaxRectsLayoutStrategy.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/textureset/TextureSetLayout.java
Labels: skip release notes

#9002 Multi-touch improvements for Android devices
  external/glfw/lib/android/android_init.c
  external/glfw/lib/android/android_util.h
  external/glfw/lib/android/android_window.c
  external/glfw/lib/input.c
  packages/glfw-2.7.1-arm64-android.tar.gz
  packages/glfw-2.7.1-arm64-ios.tar.gz
  packages/glfw-2.7.1-armv7-android.tar.gz
  packages/glfw-2.7.1-js-web.tar.gz
  packages/glfw-2.7.1-wasm-web.tar.gz
  packages/glfw-2.7.1-x86_64-ios.tar.gz
Labels: bug, engine, android, glfw

#9012 Android multitouch improvements for Hotfix 1.6.2
  engine/glfw/lib/android/android_init.c
  engine/glfw/lib/android/android_util.h
  engine/glfw/lib/android/android_window.c
  engine/glfw/lib/input.c
Labels: skip release notes

#9011 Update script_box2d_body.cpp
  engine/gamesys/src/gamesys/scripts/box2d/script_box2d_body.cpp
Labels: skip release notes
