Repository defold/defold, pull requests merged in 2024-09, with the labels that each got.

#9365 Removed debug symbols from luajit library to avoid spamming the console
  packages/luajit-2.1.0-04dca79-win32.tar.gz
  packages/luajit-2.1.0-04dca79-x86_64-win32.tar.gz
  share/ext/luajit/build_win32.bat
  share/ext/luajit/patch_2.1.0-04dca79
  share/ext/luajit/patch_2.1.0-6c4826f
Labels: skip release notes

#9296 Removed hardcoded iOS min version
  share/extender/build_input.yml
Labels: skip release notes

#9167 Always create a new vertex/index buffer when using Vulkan on OSX
  engine/graphics/src/vulkan/graphics_vulkan.cpp
Labels: skip release notes

#9385 Improved error logging from dmScript::PushTable when receiving unsupported value types
  engine/script/src/script_table.cpp
Labels: skip release notes

#9382 Add missing color into manufactured name keys
  editor/src/clj/editor/model_scene.clj
Labels: bug, editor

#9387 Added extra check for existance of jni.h
  build_tools/waf_dynamo.py
Labels: skip release notes

#9402 Mouse lock regression
  engine/platform/src/platform_window_glfw3.cpp
Labels: bug, engine, glfw

#9408 Reverse Y axis values on XInput devices (win32)
  engine/hid/src/native/hid_gamepad_driver_glfw.cpp
  engine/input/src/input.cpp
Labels: skip release notes

#9414 Added dmUtf8 to dmSDK
  engine/dlib/src/dlib/utf8.h
  engine/dlib/src/dmsdk/dlib/utf8.h
  engine/hid/src/native/hid_gamepad_driver_glfw.cpp
  engine/hid/src/native/hid_native.cpp
  engine/render/src/render/display_profiles.cpp
Labels: engine, dmsdk

#9400 Modelc jni refactor
  build_tools/waf_dynamo.py
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ModelUtilTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/AnimationSetBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ColladaUtil.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/MeshsetBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ModelUtil.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/test_model_util.sh
  engine/dlib/src/basis/transcoder/basisu_containers.h
  engine/jni/scripts/external/gen_ir.py
  engine/jni/scripts/external/gen_util.py
  engine/jni/scripts/gen_java.py
  engine/jni/src/jni/jni_util.cpp
  engine/jni/src/jni/jni_util.h
  engine/jni/src/test/wscript
  engine/jni/src/wscript
  engine/modelc/scripts/test_model_importer.sh
  engine/modelc/src/java/com/dynamo/bob/pipeline/ModelImporterJni.java
  engine/modelc/src/java/com/dynamo/bob/pipeline/Modelimporter.java
  engine/modelc/src/jni/Modelimporter_jni.cpp
  engine/modelc/src/jni/Modelimporter_jni.h
  engine/modelc/src/jni_util.cpp
  engine/modelc/src/jni_util.h
  engine/modelc/src/modelimporter.cpp
  engine/modelc/src/modelimporter.h
  engine/modelc/src/modelimporter_debug.cpp
  engine/modelc/src/modelimporter_gltf.cpp
  engine/modelc/src/modelimporter_jni.cpp
  engine/modelc/src/test/assets/Triangle.gltf
  engine/modelc/src/test/assets/simpleTriangle.bin
  engine/modelc/src/test/test_model.cpp
  engine/modelc/src/wscript
  scripts/build.py
Labels: skip release notes

#9413 Upgrade emscripten to 3.1.65
  README_EMSCRIPTEN.md
  packages/bullet-2.77-js-web.tar.gz
  packages/bullet-2.77-wasm-web.tar.gz
  packages/protobuf-3.20.1-js-web.tar.gz
  packages/protobuf-3.20.1-wasm-web.tar.gz
  scripts/build.py
  scripts/package/package_emscripten.sh
  share/extender/build_input.yml
  share/platform.sdks.json
Labels: task, html5

#9417 Fix test regressions due to WebGPU adapter
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderProgramBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderUtil.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/SPIRVReflector.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/ShaderCompilePipeline.java
  engine/gamesys/src/gamesys/test/resource/create_texture.script
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/graphics/proto/graphics/graphics_ddf.proto
  engine/graphics/src/graphics.cpp
  engine/graphics/src/graphics.h
  engine/graphics/src/graphics_private.h
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan_device.cpp
  engine/graphics/src/webgpu/graphics_webgpu.cpp
  engine/graphics/src/wscript
  engine/render/src/render/program_utils.cpp
Labels: skip release notes

#9451 Update debugging documentation
  engine/docs/NATIVE_EXTENSIONS.md
Labels: skip release notes

#9464 Improve compile_commands.json creation
  scripts/build.py
Labels: skip release notes

#9415 Added font glyph api to dmSDK
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/font/Fontc.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/FontBuilder.java
  editor/src/clj/editor/font.clj
  editor/src/clj/editor/pipeline/fontc.clj
  engine/engine/src/engine.cpp
  engine/engine/src/engine_private.h
  engine/gamesys/src/dmsdk/gamesys/resources/res_font.h
  engine/gamesys/src/dmsdk/gamesys/resources/res_gui.h
  engine/gamesys/src/dmsdk/gamesys/resources/res_label.h
  engine/gamesys/src/gamesys/components/comp_gui.cpp
  engine/gamesys/src/gamesys/components/comp_label.cpp
  engine/gamesys/src/gamesys/gamesys.cpp
  engine/gamesys/src/gamesys/resources/res_font.cpp
  engine/gamesys/src/gamesys/resources/res_font.h
  engine/gamesys/src/gamesys/resources/res_font_map.cpp
  engine/gamesys/src/gamesys/resources/res_font_map.h
  engine/gamesys/src/gamesys/resources/res_gui.cpp
  engine/gamesys/src/gamesys/resources/res_label.cpp
  engine/gamesys/src/gamesys/scripts/script_resource.cpp
  engine/gamesys/src/gamesys/test/fontview/fontview.cpp
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/render/proto/render/font_ddf.proto
  engine/render/src/dmsdk/render/render.h
  engine/render/src/render/font_renderer.cpp
  engine/render/src/render/font_renderer.h
  engine/render/src/render/font_renderer_private.h
  engine/render/src/test/test_render.cpp
  engine/render/src/test/test_render_script.cpp
  engine/resource/src/dmsdk/resource/resource.h
  engine/resource/src/dmsdk/resource/resource_gen.hpp
  engine/resource/src/resource.cpp
  engine/resource/src/resource.h
  engine/resource/wscript
Labels: engine, font

#9457 Gltf material properties are now passed to the runtime
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ModelUtil.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/MathUtil.java
  engine/gamesys/src/gamesys/resources/res_model.cpp
  engine/modelc/src/java/com/dynamo/bob/pipeline/ModelImporterJni.java
  engine/modelc/src/java/com/dynamo/bob/pipeline/Modelimporter.java
  engine/modelc/src/jni/Modelimporter_jni.cpp
  engine/modelc/src/jni/Modelimporter_jni.h
  engine/modelc/src/modelimporter.h
  engine/modelc/src/modelimporter_debug.cpp
  engine/modelc/src/modelimporter_gltf.cpp
  engine/modelc/src/modelimporter_jni.cpp
  engine/rig/proto/rig/rig_ddf.proto
  engine/rig/src/wscript
  scripts/unpack_ddf.py
Labels: 3d, gltf

#9480 Improve messages when constants and attributes are missing from the materials and compute programs
  editor/resources/templates/template.cp
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/gamesys/src/gamesys/resources/res_compute.cpp
  engine/gamesys/src/gamesys/resources/res_material.cpp
  engine/render/src/render/material.cpp
  engine/render/src/render/render.h
  engine/render/src/render/render_private.h
Labels: bug, engine

#9435 Refactor vertex attribute generation in engine
  editor/src/clj/editor/particle_lib.clj
  editor/src/java/com/defold/libs/ParticleLibrary.java
  engine/gamesys/src/gamesys/components/comp_gui.cpp
  engine/gamesys/src/gamesys/components/comp_model.cpp
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/gamesys/src/gamesys/gamesys_private.cpp
  engine/graphics/src/graphics.cpp
  engine/graphics/src/graphics.h
  engine/graphics/src/graphics_glfw_wrappers.cpp
  engine/graphics/src/graphics_util.h
  engine/graphics/src/graphics_vertices.cpp
  engine/graphics/src/test/test_graphics.cpp
  engine/graphics/src/wscript
  engine/particle/src/particle.cpp
  engine/particle/src/test/test_particle.cpp
  engine/particle/src/test/wscript
  engine/particle/src/wscript
  engine/particle/wscript
  engine/render/src/render/display_profiles.cpp
  engine/render/src/render/material.cpp
  engine/render/src/render/render.h
  engine/render/src/render/render_private.h
  engine/rig/src/dmsdk/rig/rig.h
  engine/rig/src/rig.cpp
  engine/rig/src/test/wscript
  engine/rig/src/wscript
  engine/rig/wscript
Labels: skip release notes

#9485 Editor: Add TextureImage pretty-printing to dev module
  editor/src/dev/dev.clj
Labels: task, editor, skip release notes

#9448 Add script to unpack an archive
  scripts/unpack_arc.py
  scripts/unpack_ddf.py
Labels: skip release notes

#9506 Improved output if the sdk check fails
  README_BUILD.md
  README_SETUP.md
  build_tools/sdk.py
  build_tools/waf_dynamo.py
  scripts/build.py
Labels: engine, documentation

#9472 Added dmScript::ToHash() to dmSDK
  engine/script/src/dmsdk/script/script.h
  engine/script/src/script_hash.cpp
  engine/script/src/script_msg.cpp
  engine/script/src/test/test_script_msg.cpp
Labels: engine, dmsdk

#9465 Webgpu polish (pt1)
  .clang-format
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/resources/jsweb/dmloader.js
  engine/graphics/src/webgpu/graphics_webgpu.cpp
  engine/graphics/src/webgpu/graphics_webgpu_private.h
Labels: skip release notes, webgpu
