Repository defold/defold, pull requests merged in 2025-08, with the labels that each got.

#10483 ⚠️ Removed `scale_along_z` from the engine
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/CollectionBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/CollectionBuilder.java
  editor/src/clj/editor/collection.clj
  editor/src/clj/editor/collection_common.clj
  editor/src/clj/editor/collection_non_editable.clj
  engine/dlib/src/dlib/transform.h
  engine/dlib/src/dmsdk/dlib/transform.h
  engine/dlib/src/test/test_transform.cpp
  engine/engine/src/test/label/label.script
  engine/engine/src/test/sprite/coll.script
  engine/gameobject/proto/gameobject/gameobject_ddf.proto
  engine/gameobject/src/dmsdk/gameobject/gameobject.h
  engine/gameobject/src/gameobject/comp_anim.cpp
  engine/gameobject/src/gameobject/gameobject.cpp
  engine/gameobject/src/gameobject/gameobject.h
  engine/gameobject/src/gameobject/gameobject_private.h
  engine/gameobject/src/gameobject/gameobject_script.cpp
  engine/gameobject/src/gameobject/res_collection.cpp
  engine/gameobject/src/gameobject/test/factory/test_gameobject_factory.cpp
  engine/gameobject/src/gameobject/test/script/go1.script
  engine/gamesys/src/dmsdk/gamesys/property.h
  engine/gamesys/src/gamesys/components/comp_label.cpp
  engine/gamesys/src/gamesys/components/comp_mesh.cpp
  engine/gamesys/src/gamesys/components/comp_model.cpp
  engine/gamesys/src/gamesys/components/comp_particlefx.cpp
  engine/gamesys/src/gamesys/components/comp_private.cpp
  engine/gamesys/src/gamesys/components/comp_sprite.cpp
  engine/gamesys/src/gamesys/components/comp_tilegrid.cpp
  engine/particle/src/particle.cpp
  engine/particle/src/particle.h
  engine/particle/src/particle_private.h
Labels: breaking change

#11098 Move AddDynamicResourceHash into dmsdk api
  engine/gameobject/src/dmsdk/gameobject/gameobject.h
  engine/gameobject/src/gameobject/gameobject.h
Labels: skip release notes

#11121 Remove meta.edn and use meta.properties instead
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/meta.properties
  editor/resources/live-update-meta.edn
  editor/resources/liveupdate-meta.properties
  editor/resources/meta.edn
  editor/src/clj/editor/cljfx_form_view.clj
  editor/src/clj/editor/game_project_core.clj
  editor/src/clj/editor/live_update_settings.clj
  editor/src/clj/editor/settings.clj
  editor/src/clj/editor/settings_core.clj
  editor/test/resources/save_data_project/game.project
Labels: editor, skip release notes

#11138 New splash screen "Tiny Racing"
  editor/resources/games/tinyracing.jpeg
  editor/src/java/com/defold/editor/Splash.java
Labels: skip release notes

#11136 Fix issue when debug bundle can't load
  engine/engine/src/engine.cpp
Labels: skip release notes

#11144 Fix transpilation in bob
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java
  editor/project.clj
Labels: skip release notes

#11149 DMSDK: New API to extend the GUI component with custom property getters and setters
  engine/gamesys/src/dmsdk/gamesys/components/comp_gui.h
  engine/gamesys/src/dmsdk/gamesys/gui.h
  engine/gamesys/src/gamesys/components/comp_gui.cpp
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
Labels: skip release notes
