Repository defold/defold, pull requests merged in 2025-03, with the labels that each got.

#10253 Introduce color dropper
  editor/resources/editor.fxml
  editor/src/clj/editor/boot_open_project.clj
  editor/src/clj/editor/color_dropper.clj
  editor/src/clj/editor/properties_view.clj
  editor/styling/stylesheets/components/_color-picker.scss
Labels: editor

#10289 Added missing extension finalize
  engine/engine/src/engine.cpp
Labels: skip release notes

#10297 Further cleanup of WebGPU objects:
  engine/graphics/src/webgpu/graphics_webgpu.cpp
Labels: skip release notes

#10271 Fix opengl arm64 linux
  build_tools/waf_dynamo.py
  editor/test/resources/test_project/app_manifest/vulkan.appmanifest
  engine/graphics/src/test/wscript
  engine/hid/src/test/wscript
  share/extender/build_input.yml
  share/extender/variants/headless_input.appmanifest
  share/extender/variants/release_input.appmanifest
Labels: skip release notes

#10306 Fix typo
  share/extender/variants/headless_input.appmanifest
Labels: skip release notes

#9983 GPU skinning support
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderCompilePipelineTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderPreprocessor.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilderEditor.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/ShaderCompilePipeline.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/ShaderCompilePipelineLegacy.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/util/Exec.java
  editor/resources/meta.edn
  editor/src/clj/editor/material.clj
  editor/test/resources/save_data_project/game.project
  engine/engine/content/builtins/materials/model_skinned.material
  engine/engine/content/builtins/materials/model_skinned.vp
  engine/engine/content/builtins/materials/model_skinned_instanced.material
  engine/engine/content/builtins/materials/model_skinned_instanced.vp
  engine/engine/content/builtins/materials/skinning.glsl
  engine/engine/src/engine.cpp
  engine/gamesys/src/dmsdk/gamesys/resources/res_model.h
  engine/gamesys/src/gamesys/components/comp_model.cpp
  engine/gamesys/src/gamesys/gamesys.h
  engine/gamesys/src/gamesys/gamesys_private.h
  engine/gamesys/src/gamesys/resources/res_model.cpp
  engine/gamesys/src/gamesys/test/model/invalid_vertexspace.model
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/gamesys/src/waf_gamesys.py
  engine/graphics/proto/graphics/graphics_ddf.proto
  engine/render/src/render/material.cpp
  engine/render/src/render/render.h
  engine/render/src/render/render_private.h
  engine/render/src/waf_render.py
  engine/rig/src/rig.cpp
  engine/rig/src/rig.h
  engine/rig/src/rig_private.h
  engine/rig/src/test/test_rig.cpp
Labels: engine, model, graphics, render

#10300 Output crosscompilation errors from pipeline
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderCompilePipelineTest.java
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderProgramBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilderEditor.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/ShaderCompilePipeline.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/ShaderCompilePipelineLegacy.java
  engine/shaderc/src/java/com/dynamo/bob/pipeline/Shaderc.java
  engine/shaderc/src/java/com/dynamo/bob/pipeline/ShadercJni.java
  engine/shaderc/src/jni/Shaderc_jni.cpp
  engine/shaderc/src/jni/Shaderc_jni.h
  engine/shaderc/src/shaderc.h
  engine/shaderc/src/shaderc_jni.cpp
  engine/shaderc/src/shaderc_spirv.cpp
  engine/shaderc/src/shaderc_spvc.cpp
Labels: bob, graphics, pipeline, shader

#10313 Create texture script regression
  engine/gamesys/src/gamesys/gamesys_resource.cpp
  engine/gamesys/src/gamesys/resources/res_texture.cpp
Labels: engine, graphics

#10303 Make sure that parameters from `game.project` may invalidate bob cache
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/cache/test/ResourceCacheKeyTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/CollisionObjectBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/CopyBuilders.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/MeshsetBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/OggBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ScriptBuilders.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilder.java
Labels: skip release notes

#10298 Create atlas images on drag & drop from the asset tree
  editor/src/clj/editor/atlas.clj
  editor/src/clj/editor/input.clj
  editor/src/clj/editor/scene.clj
Labels: editor

#10284 Add callbacks for progress and completed load
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/resources/jsweb/dmloader.js
Labels: feature request, html5

#10325 Install physics adapter before creating the world
  engine/engine/src/test/game.project
  engine/engine/src/test/issue-10323/issue-10323.collection
  engine/engine/src/test/issue-10323/issue-10323.script
  engine/engine/src/test/main.collection
  engine/engine/src/test/test_engine.cpp
  engine/gamesys/src/gamesys/components/box2d/comp_collision_object_box2d.cpp
Labels: skip release notes

#10311 Build setup improvements
  scripts/build.py
Labels: skip release notes

#10331 Review fixes
  editor/src/clj/editor/boot_open_project.clj
  editor/src/clj/editor/editor_extensions.clj
  editor/src/clj/editor/editor_extensions/coerce.clj
  editor/src/clj/editor/editor_extensions/docs.clj
  editor/src/clj/editor/editor_extensions/runtime.clj
  editor/src/clj/editor/resource.clj
  editor/src/clj/editor/web_server.clj
  editor/src/clj/util/http_server.clj
  editor/test/integration/editor_extensions_test.clj
  editor/test/integration/web_server_test.clj
Labels: skip release notes

#10123 Create 3d textures via resource.create_texture
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilder.java
  engine/gamesys/src/gamesys/components/comp_gui.cpp
  engine/gamesys/src/gamesys/gamesys_private.h
  engine/gamesys/src/gamesys/gamesys_resource.cpp
  engine/gamesys/src/gamesys/resources/res_render_target.cpp
  engine/gamesys/src/gamesys/resources/res_texture.cpp
  engine/gamesys/src/gamesys/resources/res_texture.h
  engine/gamesys/src/gamesys/scripts/script_resource.cpp
  engine/gamesys/src/gamesys/test/resource/create_texture.script
  engine/graphics/proto/graphics/graphics_ddf.proto
  engine/graphics/src/dmsdk/graphics/graphics.h
  engine/graphics/src/graphics.cpp
  engine/graphics/src/graphics.h
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/opengl/graphics_opengl_private.h
  engine/graphics/src/vulkan/graphics_vulkan.cpp
  engine/graphics/src/vulkan/graphics_vulkan_device.cpp
  engine/graphics/src/vulkan/graphics_vulkan_private.h
  engine/graphics/src/vulkan/graphics_vulkan_swap_chain.cpp
  engine/render/src/render/program_utils.cpp
  engine/script/src/script_graphics.cpp
Labels: engine, graphics, render

#10351 Merge shader resources
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderCompilePipelineTest.java
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderProgramBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilder.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/SPIRVReflector.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/ShaderCompilePipeline.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/shader/ShaderCompilePipelineLegacy.java
  engine/shaderc/src/java/com/dynamo/bob/pipeline/Shaderc.java
  engine/shaderc/src/java/com/dynamo/bob/pipeline/ShadercJni.java
  engine/shaderc/src/jni/Shaderc_jni.cpp
  engine/shaderc/src/jni/Shaderc_jni.h
  engine/shaderc/src/shaderc.cpp
  engine/shaderc/src/shaderc.h
  engine/shaderc/src/shaderc_jni.cpp
  engine/shaderc/src/shaderc_private.h
  engine/shaderc/src/shaderc_spvc.cpp
  engine/shaderc/src/test/test_shaderc.cpp
Labels: engine, graphics, pipeline

#10355 Use vulkan as default renderer on osx
  build_tools/waf_dynamo.py
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/cache/test/ResourceCacheKeyTest.java
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/ShaderProgramBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Bob.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderCompilers.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/ShaderProgramBuilder.java
  editor/src/clj/editor/app_manifest.clj
  editor/test/integration/app_manifest_test.clj
  editor/test/resources/test_project/app_manifest/opengl_osx.appmanifest
  editor/test/resources/test_project/app_manifest/vulkan_and_opengl_osx.appmanifest
  engine/engine/src/wscript
  engine/engine/wscript
  engine/graphics/src/null/graphics_null.cpp
  engine/graphics/src/vulkan/graphics_vulkan_context.cpp
  share/extender/build_input.yml
Labels: engine, macos, vulkan

#10360 Use latest rive + fix issues in editor tests
  editor/project.clj
  editor/test/resources/rive_project/bones/bones.collection
  editor/test/resources/save_data_project/checked.rivemodel
Labels: skip release notes

#10367 Fix multi-editing of gui node properties
  editor/src/clj/editor/gui.clj
Labels: bug, editor

#10374 Added missed libraries in app manifest for Vulkan variant for linux platform
  editor/src/clj/editor/app_manifest.clj
  editor/test/resources/test_project/app_manifest/vulkan.appmanifest
  editor/test/resources/test_project/app_manifest/vulkan_and_opengl.appmanifest
Labels: skip release notes

#10385 Support 3d images for OpenGL
  engine/graphics/src/opengl/graphics_opengl.cpp
  engine/graphics/src/opengl/graphics_opengl_defines.h
Labels: skip release notes

#10395 Use full texture dimensions in res_texture when uploading specific mipmaps
  engine/gamesys/src/gamesys/resources/res_texture.cpp
  engine/gamesys/src/gamesys/test/resource/set_texture.script
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
Labels: skip release notes

#10357 Projects can list paths to not load in .defunload
  editor/.gitignore
  editor/.idea/codeStyles/Project.xml
  editor/.idea/inspectionProfiles/Project_Default.xml
  editor/project.clj
  editor/src/clj/dynamo/graph.clj
  editor/src/clj/editor/app_view.clj
  editor/src/clj/editor/asset_browser.clj
  editor/src/clj/editor/atlas.clj
  editor/src/clj/editor/code/text_file.clj
  editor/src/clj/editor/code/transpilers.clj
  editor/src/clj/editor/collection.clj
  editor/src/clj/editor/collection_common.clj
  editor/src/clj/editor/collection_non_editable.clj
  editor/src/clj/editor/collection_proxy.clj
  editor/src/clj/editor/defold_project.clj
  editor/src/clj/editor/defold_project_search.clj
  editor/src/clj/editor/dialogs.clj
  editor/src/clj/editor/factory.clj
  editor/src/clj/editor/font.clj
  editor/src/clj/editor/fxui.clj
  editor/src/clj/editor/game_object.clj
  editor/src/clj/editor/game_object_common.clj
  editor/src/clj/editor/game_object_non_editable.clj
  editor/src/clj/editor/game_project.clj
  editor/src/clj/editor/gui.clj
  editor/src/clj/editor/model.clj
  editor/src/clj/editor/outline.clj
  editor/src/clj/editor/placeholder_resource.clj
  editor/src/clj/editor/protobuf.clj
  editor/src/clj/editor/resource.clj
  editor/src/clj/editor/resource_dialog.clj
  editor/src/clj/editor/resource_node.clj
  editor/src/clj/editor/resource_watch.clj
  editor/src/clj/editor/sprite.clj
  editor/src/clj/editor/tile_source.clj
  editor/src/clj/editor/validation.clj
  editor/src/clj/editor/workspace.clj
  editor/src/clj/internal/system.clj
  editor/src/clj/internal/transaction.clj
  editor/src/clj/util/debug_util.clj
  editor/src/clj/util/eduction.clj
  editor/src/clj/util/fn.clj
  editor/src/dev/load_project.clj
  editor/test/editor/defold_project_search_test.clj
  editor/test/editor/pipeline_test.clj
  editor/test/editor/protobuf_types_test.clj
  editor/test/editor/resource_test.clj
  editor/test/integration/build_test.clj
  editor/test/integration/reload_test.clj
  editor/test/integration/save_test.clj
  editor/test/integration/scope_test.clj
  editor/test/integration/sparse_protobuf_test.clj
  editor/test/integration/test_util.clj
  editor/test/integration/unload_test.clj
  editor/test/resources/save_data_project/.defunload
  editor/test/resources/save_data_project/referenced/unloaded.gui
  editor/test/util/eduction_test.clj
Labels: feature request, editor

#10403 Fix building with legacy box2d from editor
  editor/src/clj/editor/app_manifest.clj
  editor/test/resources/test_project/app_manifest/physics_2d_legacy.appmanifest
  engine/physics/src/physics/box2d_defold/box2d_defold_physics.cpp
Labels: skip release notes

#10405 Editor: Replace all calls to workspace/project-path with the new project-directory function
  editor/src/clj/editor/animation_set.clj
  editor/src/clj/editor/app_view.clj
  editor/src/clj/editor/asset_browser.clj
  editor/src/clj/editor/changes_view.clj
  editor/src/clj/editor/cljfx_form_view.clj
  editor/src/clj/editor/disk.clj
  editor/src/clj/editor/editor_extensions.clj
  editor/src/clj/editor/editor_extensions/actions.clj
  editor/src/clj/editor/engine/native_extensions.clj
  editor/src/clj/editor/lsp/server.clj
  editor/src/clj/editor/markdown.clj
  editor/src/clj/editor/model_loader.clj
  editor/src/clj/editor/pipeline/bob.clj
  editor/src/clj/editor/scene.clj
  editor/src/clj/editor/workspace.clj
  editor/src/dev/dev.clj
  editor/test/editor/build_target_test.clj
  editor/test/editor/engine/build_errors_test.clj
  editor/test/integration/app_view_test.clj
  editor/test/integration/asset_browser_test.clj
  editor/test/integration/build_test.clj
  editor/test/integration/editor_extensions_test.clj
  editor/test/integration/engine/native_extensions_test.clj
  editor/test/integration/library_test.clj
  editor/test/integration/reload_test.clj
  editor/test/integration/resource_watch_test.clj
  editor/test/integration/save_test.clj
  editor/test/integration/script_properties_test.clj
  editor/test/integration/script_test.clj
  editor/test/integration/sparse_protobuf_test.clj
  editor/test/integration/web_server_test.clj
Labels: task, editor, skip release notes
