Repository defold/defold, pull requests merged in 2025-09, with the labels that each got.

#11052 Set PBR properties for shaders
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/MaterialBuilderTest.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/pipeline/MaterialBuilder.java
  editor/src/clj/editor/code/shader_compilation.clj
  editor/src/clj/editor/material.clj
  editor/src/clj/editor/model_scene.clj
  editor/src/clj/util/digestable.clj
  editor/test/integration/material_test.clj
  editor/test/resources/test_project/materials/test_pbr_materials.material
  editor/test/resources/test_project/materials/test_pbr_parameters.fp
  engine/gamesys/src/gamesys/components/comp_model.cpp
  engine/gamesys/src/gamesys/components/comp_private.cpp
  engine/gamesys/src/gamesys/components/comp_private.h
  engine/gamesys/src/gamesys/gamesys_private.h
  engine/gamesys/src/gamesys/resources/res_compute.cpp
  engine/gamesys/src/gamesys/resources/res_material.cpp
  engine/gamesys/src/gamesys/test/create_prebuilts.sh
  engine/gamesys/src/gamesys/test/mesh_prebuilt_project/main/main.collection
  engine/gamesys/src/gamesys/test/mesh_prebuilt_project/model/empty.glb
  engine/gamesys/src/gamesys/test/mesh_prebuilt_project/model/pbr.fp
  engine/gamesys/src/gamesys/test/mesh_prebuilt_project/model/pbr.material
  engine/gamesys/src/gamesys/test/mesh_prebuilt_project/model/pbr_properties.gltf
  engine/gamesys/src/gamesys/test/mesh_prebuilt_project/model/pbr_properties.model
  engine/gamesys/src/gamesys/test/mesh_prebuilt_project/model/pbr_properties_textured.gltf
  engine/gamesys/src/gamesys/test/mesh_prebuilt_project/model/pbr_properties_textured.model
  engine/gamesys/src/gamesys/test/model/aabb_model.prebuilt_modelc
  engine/gamesys/src/gamesys/test/model/empty.prebuilt_modelc
  engine/gamesys/src/gamesys/test/model/pbr.fp
  engine/gamesys/src/gamesys/test/model/pbr.material
  engine/gamesys/src/gamesys/test/model/pbr_properties.go
  engine/gamesys/src/gamesys/test/model/pbr_properties.prebuilt_meshsetc
  engine/gamesys/src/gamesys/test/model/pbr_properties.prebuilt_modelc
  engine/gamesys/src/gamesys/test/model/pbr_properties.prebuilt_rigscenec
  engine/gamesys/src/gamesys/test/model/pbr_properties.prebuilt_skeletonc
  engine/gamesys/src/gamesys/test/model/pbr_properties_textured.prebuilt_meshsetc
  engine/gamesys/src/gamesys/test/model/pbr_properties_textured.prebuilt_modelc
  engine/gamesys/src/gamesys/test/model/pbr_properties_textured.prebuilt_rigscenec
  engine/gamesys/src/gamesys/test/model/pbr_properties_textured.prebuilt_skeletonc
  engine/gamesys/src/gamesys/test/model/several_meshes.prebuilt_modelc
  engine/gamesys/src/gamesys/test/test_gamesys.cpp
  engine/gamesys/src/gamesys/test/test_gamesys.h
  engine/render/proto/render/material_ddf.proto
  engine/render/src/render/compute.cpp
  engine/render/src/render/material.cpp
  engine/render/src/render/render.h
  engine/render/src/render/render_private.h
  engine/render/src/waf_render.py
  engine/rig/proto/rig/rig_ddf.proto
Labels: feature request, engine, render, gltf

#11188 Fix property context menu
  editor/src/clj/editor/properties_view.clj
Labels: skip release notes

#11189 Decrease editor size by 12 MB
  editor/.gitignore
  editor/LSPSnippet.g4
  editor/project.clj
  editor/src/clj/editor/code_completion.clj
  editor/tasks/leiningen/init.clj
Labels: editor

#11187 Hotfix for PBR parameters merge
  engine/gamesys/src/gamesys/components/comp_model.cpp
Labels: skip release notes

#11240 Fix how glfw header are packed
  scripts/build.py
Labels: skip release notes

#11255 Localize many dialogs
  editor/AGENTS.md
  editor/resources/localization/en.editor_localization
  editor/resources/localization/ru.editor_localization
  editor/src/clj/editor/app_view.clj
  editor/src/clj/editor/asset_browser.clj
  editor/src/clj/editor/atlas.clj
  editor/src/clj/editor/boot.clj
  editor/src/clj/editor/boot_open_project.clj
  editor/src/clj/editor/changes_view.clj
  editor/src/clj/editor/cljfx_form_view.clj
  editor/src/clj/editor/code/preprocessors.clj
  editor/src/clj/editor/code/transpilers.clj
  editor/src/clj/editor/collection.clj
  editor/src/clj/editor/debug_view.clj
  editor/src/clj/editor/defold_project.clj
  editor/src/clj/editor/dialogs.clj
  editor/src/clj/editor/diff_view.clj
  editor/src/clj/editor/engine.clj
  editor/src/clj/editor/game_object.clj
  editor/src/clj/editor/gui.clj
  editor/src/clj/editor/localization.clj
  editor/src/clj/editor/recent_files.clj
  editor/src/clj/editor/resource_dialog.clj
  editor/src/clj/editor/shared_editor_settings.clj
  editor/src/clj/editor/targets.clj
  editor/src/clj/editor/texture/engine.clj
  editor/src/clj/editor/ui/updater.clj
  editor/src/clj/editor/welcome.clj
  editor/src/clj/editor/workspace.clj
  editor/src/dev/load_project.clj
  editor/styling/stylesheets/modules/_welcome-dialog.scss
  editor/test/editor/defold_project_test.clj
  editor/test/integration/app_view_test.clj
  editor/test/integration/asset_browser_test.clj
  editor/test/integration/form_type_preservation_test.clj
  editor/test/integration/lsp_test.clj
  editor/test/integration/reload_test.clj
  editor/test/integration/save_test.clj
  editor/test/integration/test_util.clj
Labels: editor, skip release notes

#11266 Added missing function stubs to OpenAL sound backend
  engine/sound/src/sound_openal.cpp
  engine/sound/src/test/wscript
Labels: skip release notes
