Repository defold/defold, pull requests merged in 2025-07, with the labels that each got.

#10927 Make build report compact in console
  build_tools/BuildTimeTracker.py
Labels: skip release notes

#10934 Slightly reduce binary size
  engine/gamesys/src/gamesys/gamesys.cpp
  engine/gamesys/src/gamesys/gamesys_private.h
  engine/render/src/render/render.cpp
  engine/render/src/render/render.h
Labels: skip release notes

#10974 Allow debugging of macOS builds
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/BundleHelper.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/MacOSBundler.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/bundle/resources/macos/entitlements-debug.plist
Labels: feature request, engine

#10981 Restore ancidently removed public API
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java
Labels: skip release notes

#11002 Fix issue with search in path cache.
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/pipeline/BundleResourcesTest.java
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/test/ProjectTest.java
  com.dynamo.cr/com.dynamo.cr.bob.test/src/com/dynamo/bob/test/TestLibrariesRule.java
  com.dynamo.cr/com.dynamo.cr.bob/src/com/dynamo/bob/Project.java
Labels: skip release notes

#11013 Make skinning shader compatible with OpenGL ES 2.0 and WebGL 1.
  engine/engine/content/builtins/materials/skinning.glsl
Labels: html5, skip release notes

#11027 Cancel outline rename on context menu request and consume context menu auto hide events
  editor/src/clj/editor/outline_view.clj
  editor/src/clj/editor/ui.clj
Labels: skip release notes

#11031 Fix remotery crash on reboot
  engine/profiler/src/remotery/profiler_remotery.cpp
Labels: skip release notes
